### ISSUE TITLE
add some kind of "JDK compatibility" guide

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#1000]
it would say that Scala 2.10.x works fine on Java 6, 7, and 8 (is there a minimum version that works well on 8?), and 2.10.7 has minimal Java 9 support that is unlikely to improve further

likewise for 2.11.x; 2.11.12 is the release that added minimal Java 9 support

2.12.x requires Java 8 minimum; 2.12.4 is the first version with minimal Java 9 support

and then maybe some content inspired by https://github.com/scala/scala-dev/issues/139 about remaining issues and/or missing features

I'm sure there's more to say, but that could be the initial skeleton

this would go under http://docs.scala-lang.org/overviews/index.html

**Comment by SethTisue** [comment]
is there a volunteer who would like to draft a first version...?

**Comment by smarter** [comment]
The guide should also mention that Java 9 support requires sbt 0.13.17 or 1.1.0 (I think ?). Technically older versions of sbt work if you use a recent sbt launcher but good luck explaining to people that they need to upgrade it. They probably unzipped a tarball somewhere 5 years ago and have no idea how to update it.

**Comment by colindean** [comment]
I took a stab at this just now in #1005.
