### ISSUE TITLE
404 on SIP-23 42.type

### ISSUE THREAD

**Issue by OlivierBlanvillain** [scala/docs.scala-lang#1047]
http://docs.scala-lang.org/sips/pending/42.type.html
got moved to 
https://docs.scala-lang.org/sips/42.type.html

All links to the first URL are now broken links :crying_cat_face: 

It would be nice to have the CI check than PRs do not remove any pages than are currently published online.

**Comment by smarter** [comment]
In fact, the old link was wrong and outdated, but it took a while for it to get removed: https://github.com/scala/docs.scala-lang/issues/872

**Comment by SethTisue** [comment]
a PR adding the appropriate `redirect_from`s would be very welcome

**Comment by SethTisue** [comment]
and I agree we should be more vigilant in the future about catching this during PR review instead of later. `redirect_from`s are easy to add.

**Comment by jvican** [comment]
> and I agree we should be more vigilant in the future about catching this during PR review instead of later. redirect_froms are easy to add.

I'll do it. I need to know for certainty that only links in `sip/pending` were removed, I'll be working under that assumption for now.

**Comment by jvican** [comment]
Fixed in master given its urgency. Commit is https://github.com/scala/docs.scala-lang/commit/6ab4af402c2af0b2f2d61c088295957a45239e98, but the latest one fixes some broken links and makes the link checker pass https://platform-ci.scala-lang.org/scala/docs.scala-lang/418. CI is happy again.
