### ISSUE TITLE
scala documentation is creating problem for newbie

### ISSUE THREAD

**Issue by anupash147** [scala/docs.scala-lang#1053]
in the documentation : https://docs.scala-lang.org/getting-started-intellij-track/getting-started-with-scala-in-intellij.html. The first program never executes for a newbie. There couple of blogs to this problem ref https://intellij-support.jetbrains.com/hc/en-us/community/posts/206256109-Weird-Scala-issue-with-10-0-2?page=1#community_comment_206591415. But the solution would be just to fix it at the root. Please change the program from 
```
object Hello extends App {
  println("Hello, World!")
}
```

to
```
object Hello {

  def main(args: Array[String]): Unit =

    println("Hello, world.")

}
``` 

This would atleast get running in intellij without any pain

**Comment by NthPortal** [comment]
I am running the latest version of IntelliJ IDEA Community Edition, and it works fine for me. While it is possible that it didn't work in 2011, it works in the current version of IntelliJ.

The example can be run using either the run icon in the gutter, or the context menu as described in the "Getting Started" documentation, as shown in the screenshots below.

I suspect that your project is not configured correctly, but this is not the right place to ask for help getting it to run. I recommend asking on [users.scala-lang.org](https://users.scala-lang.org), the [Scala Gitter room](https://gitter.im/scala/scala), or an IntelliJ forum.

![Run from gutter icon](https://user-images.githubusercontent.com/7505383/38963367-8b4c48d2-433f-11e8-97b0-5717690a008b.png)
![Run from context menu](https://user-images.githubusercontent.com/7505383/38963408-b87ada58-433f-11e8-8cea-d85e1e511104.png)

**Comment by SethTisue** [comment]
@anupash147 I agree with @NthPortal that:

* the 2011 thing you've linked to is something else entirely
* it's not really plausible that IntelliJ can't deal with `object Hello extends App { ...` 

we appreciate the report and we know you're trying to help, but we'd need corroboration that the change you're requesting is actually a right change. perhaps there's _some_ improvement that could be made to our doc here, but I'm not convinced avoiding `extends App` is it.
