### ISSUE TITLE
BUILDING A SCALA PROJECT WITH INTELLIJ AND SBT

### ISSUE THREAD

**Issue by haoli-buaa** [scala/docs.scala-lang#1073]
Hi, guys
I am rather new to scala. 
I created a project as the instruction page told me. 
But got an type dismatch error.

The error info goes likes this:
```
[error]  found   : Seq[Int]
[error]  required: Array[String]
[error]   val args = Seq(1, 2, 5, 9, 8, 6)
```

Can somebody give me some hint on what went wrong here?

**Comment by fs19910227** [comment]
what is the code like?

**Comment by haoli-buaa** [comment]
Code:
```object Main extends App {
  val ages = Seq(42, 75, 29, 64)
  println(s"The oldest person is ${ages.max}")
}
```

Compile passed by changing the line to 
```
override val args = Array("1", "2")
```

**Comment by haoli-buaa** [comment]
Just want to confirm whether there is a mistake in the [official doc](https://docs.scala-lang.org/getting-started-intellij-track/building-a-scala-project-with-intellij-and-sbt.html)

**Comment by SethTisue** [comment]
`App` already has a member called `args`. So if you add a new `val`, it matters whether that `val` is called `args` or something else like `ages`. If you call it `args`, its type has to match (or refine) the type of the existing member.

The doc suggests using `ages`, so I don't see that there's a mistake in the doc.

**Comment by haoli-buaa** [comment]
Thanks a lot. @SethTisue
