### ISSUE TITLE
Chinese users can't get to jquery

### ISSUE THREAD

**Issue by dm520** [scala/docs.scala-lang#1074]
Chinese users can't get to jquery。
 https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
Please use the local server to store the jQuery file

**Comment by NthPortal** [comment]
You can also potentially use a variety of fallback CDNs, and finally fall
back to local if none of them work. haveibeenpwned does this

**Comment by SethTisue** [comment]
a pull request on this would be welcome

**Comment by jvican** [comment]
I'm sorry, closing was an accident. @NthPortal thanks for looking into this, it looks like we'll need some input from Chinese users to take a decision and test the implementation. /cc @hepin1989
