### ISSUE TITLE
The style guide doesn't teach me the hard parts

### ISSUE THREAD

**Issue by Jasper-M** [scala/docs.scala-lang#1087]
Today I was wondering whether there's a decent way to write `if else` expressions that require curly braces:

```
if (foo) {
  val a = getAnA()
  giveMeAB(a, b)
} else b

if (foo) {
  val a = getAnA()
  giveMeAB(a, b)
} else {
  b
}

if (foo) {
  val a = getAnA()
  giveMeAB(a, b)
} 
else b

if (foo) {
  val a = getAnA()
  giveMeAB(a, b)
} 
else {
  b
}
```

None of these look 100% satisfying... It seems to me that this is actually the hard question about styling `if else` expressions with the current Scala syntax. But the [style guide](https://docs.scala-lang.org/style/control-structures.html) doesn't even mention it.

**Comment by SethTisue** [comment]
I don't think there's a consensus on this. All of these alternatives seem like plausible things I might see in real projects.

Usually the style guide remains silent on issues for which there is no consensus style.
