### ISSUE TITLE
The architecture of scala collections should have a link to the 2.13 sister page

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/docs.scala-lang#1121]
This page: https://docs.scala-lang.org/overviews/core/architecture-of-scala-collections.html
Should link to that page: https://docs.scala-lang.org/overviews/core/architecture-of-scala-213-collections.html#inner-main

Something like a warning on the top of the old documentation that you should be looking at the 2.13.x page.

**Comment by SethTisue** [comment]
PR: https://github.com/scala/docs.scala-lang/pull/1456
