### ISSUE TITLE
Please add Scala Native Gitter channel

### ISSUE THREAD

**Issue by ekrich** [scala/docs.scala-lang#1139]
It would be nice if `scala-native/scala-native` would be added to the following page. https://www.scala-lang.org/community/

**Comment by SethTisue** [comment]
totally agree! pull request? (you, or, somebody?)

**Comment by ekrich** [comment]
It looks like the info is dynamically generated via `site.data.chats-forums.gitterChannels`. Any idea where that is or how it works?

**Comment by byeonggukgong** [comment]
@SethTisue @ekrich If you guys really want to add Scala Native Gitter channel, I'll PR. Can I try?
