### ISSUE TITLE
Include/explain iterator laziness in overview documentation

### ISSUE THREAD

**Issue by ksilin** [scala/docs.scala-lang#1145]
The [documentation of `Iterator#map`](https://www.scala-lang.org/api/current/scala/collection/Iterator.html#map[B](f:A=%3EB):Iterator[B]) explains the lazy nature correctly, once you know about iterator laziness already. However, the implications for side-effecting applications of `map` can surprise developers new to Scala (as it did surprise me)

An aside on the implications of laziness in the [Iterator overview docs](https://docs.scala-lang.org/overviews/collections/iterators.html#) would be very helpful.

**Comment by ksilin** [comment]
replaces https://github.com/scala/bug/issues/11145

**Comment by rkoeninger** [comment]
FYI, this is up at https://docs.scala-lang.org/overviews/collections/iterators.html#laziness
