### ISSUE TITLE
Page Contributors shows as sub-heading in ToC

### ISSUE THREAD

**Issue by rkoeninger** [scala/docs.scala-lang#1148]
Just noticed something weird about how the table of contents is structured.

The generated "Contributors to this Page" section at the bottom of each page gets shown as a sub-heading in the ToC when it logically isn't:

(Contributors is not a sub-section of Structural Types)

![image](https://user-images.githubusercontent.com/6507761/45717311-92940580-bb67-11e8-81d6-b9d1d1f887c6.png)

Two quick ways of fixing it:

1. Adding `.content-contributors` in the `exclude` list when calling the toc plugin, so it doesn't show up in the ToC, see here:

https://github.com/scala/docs.scala-lang/blob/5ac9c209ec572f1be183ce8e6c55d2f2cd9d9f72/resources/js/functions.js#L298-L309

2. Or make the contributors heading an `h2` so it's on the same level as the previous heading and won't get nested under it:

https://github.com/scala/docs.scala-lang/blob/5ac9c209ec572f1be183ce8e6c55d2f2cd9d9f72/_includes/contributors-list.html#L1-L4

We can decide the preferred approach and I'll open a PR with the fix.

**Comment by SethTisue** [comment]
I don't have an opinion either way... anybody else?

**Comment by rkoeninger** [comment]
I instead tried option 3, which is to have the `.toc` function use an ad-hoc `toc-context` class instead of the incidental `inner-box`. Divs that contain information you want to show in the TOC would now have `toc-context` added to their class list. If the content you want on the TOC has sibling content that you don't want on the TOC, move the TOC-targeted content into a nested div with `class="toc-context"`. e.g.

```html
<div class="inner-box">
  <div class="toc-context">
    {{content}}
  </div>

  {% include contributors-list.html %}
</div>
```

Started working on a PR for this.
