### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by JamesYeoman** [scala/docs.scala-lang#1149]
When I click "Next" on the introduction page, I get taken to what appears to be a Chinese page and the English equivalent of that page is "tutorials/tour/basics.html.html"

EDIT

The "introduction" page is [this](https://docs.scala-lang.org/tutorials/tour/tour-of-scala.html.html)

The page that I get sent to when I click next is [this](https://docs.scala-lang.org/zh-cn/tour/basics.html)

The page that I should get sent to when I click next on the introduction page is [this](https://docs.scala-lang.org/tutorials/tour/basics.html.html)

EDIT 2
Going through the docs more, every page has broken links that go to the "zh-cn" site. The links on the right-hand-side work fine. It's the links in the main section of the page that are broken (for example, in "basics", there's a link in the Classes section that should take me to the English Classes page. But it takes me to the "zh-cn" site).

**Comment by SethTisue** [comment]
@JamesYeoman thanks, very glad you caught & reported this. if it doesn't seem fixed to you, let us know

**Comment by NishanthSpShetty** [comment]
Im still facing this issue on doc pages on both next and previous links. check [this](https://docs.scala-lang.org/tutorials/tour/classes.html.html) page.
