### ISSUE TITLE
CI build failing due to external links

### ISSUE THREAD

**Issue by rkoeninger** [scala/docs.scala-lang#1168]
My PR builds (#1165 and #1167) are failing when checking external links on the `www.oracle.com` domain. These pages are accessible to the browser but when I tried them from my machine in Fiddler, they return 403 like the build log reports. And curl can fetch them successfully from my machine.

This doesn't appear to be happening for other PR's (e.g. #1166) even though they have the same links on their branch, and I didn't touch oracle links or the pages containing them on my branches.

Anyone know what the issue is?

(making the link https did not help)

Build log excerpt:

```
+ bundle exec htmlproofer ./_site/ --only-4xx --http-status-ignore 401,429 --empty-alt-ignore --allow-hash-href --url-ignore '/https://github.com/scala/docs.scala-lang/blob/master/.*/'
Running ["ImageCheck", "LinkCheck", "ScriptCheck"] on ["./_site/"] on *.html... 
Checking 887 external links...
Ran on 649 files!
- ./_site/getting-started-intellij-track/getting-started-with-scala-in-intellij.html
  *  External link http://www.oracle.com/technetwork/java/javase/downloads/index.html failed: 403 No error
htmlproofer 3.9.1 | Error:  HTML-Proofer found 1 failure!
```

**Comment by SethTisue** [comment]
looks like we need a version of https://github.com/scala/scala-lang/pull/961 in this repo
