### ISSUE TITLE
Rename the "Abstract type" page?

### ISSUE THREAD

**Issue by dwijnand** [scala/docs.scala-lang#1214]
The page https://docs.scala-lang.org/tour/abstract-types.html is actually about abstract type members (which require the enclosing type to be abstract) and not about abstract types in general (i.e https://en.wikipedia.org/wiki/Abstract_type).

What do you think about renaming it and tweaking the first sentence to explain?

**Comment by SethTisue** [comment]
agree

**Comment by dwijnand** [comment]
Should we be concerned with redirecting the old URL?  If so, is there prior art I can copy?

**Comment by SethTisue** [comment]
yes, I think it's worth adding a redirect, I think `redirect_from` would do the trick
