### ISSUE TITLE
Make the glossary translatable

### ISSUE THREAD

**Issue by sadhen** [scala/docs.scala-lang#1224]

**Comment by SethTisue** [comment]
yes, a pull request on this would be welcome

**Comment by dongxuwang** [comment]
@SethTisue can you help make a zh-cn skeleton of glossary so that I can add the Chinese Simplified

**Comment by dongxuwang** [comment]
I've tried to add the skeleton according to 'cheatsheet', but the dropdown for selecting languages failed to show in the zh-cn page.

**Comment by SethTisue** [comment]
I don't have enough experience with how the translations stuff works (in Jekyll in generally, or in our setup specifically) to offer assistance off the top of my head. perhaps someone else watching the repo could look at it...?

**Comment by dongxuwang** [comment]
Ok, after some researching I know how to cope with it. I am going to summit a pr for the skeleton together with the zh-cn translation.

**Comment by dongxuwang** [comment]
Finally, PR is #1378 
This is really a huge commit for only one page(_zh_cn/glossary/index.md). However, it is recommended and worthwhile to read throughout the glossary, which is the "meta-language" of Scala after all.

**Comment by exoego** [comment]
I think this issue is closable since #1378 made the glossary translatable.

**Comment by dongxuwang** [comment]
I guess so.
