### ISSUE TITLE
There is no New => Scala class option

### ISSUE THREAD

**Issue by ryancrawcour** [scala/docs.scala-lang#1308]
When following the steps here, I try and add my new Scala class but alas, there is no option for New => Scala class.

I only have things like Java Class or Kotlin Class.

What gives?

**Comment by Philippus** [comment]
Assuming that you are using IntelliJ as you're mentioning Kotlin. Did you performs step 3 of the Installation? https://docs.scala-lang.org/getting-started-intellij-track/getting-started-with-scala-in-intellij.html (installing the Scala plugin)

**Comment by SethTisue** [comment]
that seems almost certain to be the problem
