### ISSUE TITLE
To polish Nested Method

### ISSUE THREAD

**Issue by pontsh** [scala/docs.scala-lang#1321]
#### I think this verison is more comprehensable to many people

```
  def factorial(x: Int): Int = {
    if(x == 1) x
    else x * factorial(x-1)
  }
```

**Comment by SethTisue** [comment]
what page does this refer to?

**Comment by SethTisue** [comment]
I assume this refers to https://docs.scala-lang.org/tour/nested-functions.html

the whole point of that page is to demonstrate nested functions, so replacing it with a non-nested version doesn't make sense

if we do stick with the factorial example, the page should probably say that the point of using a nested method with an accumulator is to be tail-recursive

but also, perhaps a different example entirely would be better. but I don't have an idea for one right now
