### ISSUE TITLE
Localized landing pages and UX

### ISSUE THREAD

**Issue by eed3si9n** [scala/docs.scala-lang#1324]
The Scala Documentation site contains many localized contents that various language community have put in efforts over the years. For example, [the entire collections docs](https://docs.scala-lang.org/ja/overviews/collections/introduction.html) are translated into Japanese, Tour of Scala lists nine languages including Spanish, Standard Chinese, Korean, etc.

It would be nice if we can create a landing page for each language, similar to what Wikipedia has https://es.wikipedia.org/wiki/Wikipedia:Portada, and link to the available localized contents.

Prior to 2017 redesign, there used to be a link to localized overview page from the English overview page:
- https://web.archive.org/web/20170611072332/http://docs.scala-lang.org/ja/overviews

I think having top-level localized landing pages would motivate the various language communities to fill the gaps, and over time improve the usability by non-English-speaking learners of Scala.

**Comment by kotobotov** [comment]
it's also good for search engine optimisation
