### ISSUE TITLE
Out of date partest tutorial

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/docs.scala-lang#1328]
I stumbled upon https://docs.scala-lang.org/tutorials/partest-guide.html

This page is out of date, and I also can't find where it's generated to update it.

**Comment by ashawley** [comment]
It was deleted in 967d959, but because of the way the site publishes the old files aren't deleted.

You can create a redirect to overwrite the file, or restore the file and update it.

**Comment by martijnhoekstra** [comment]
I don't think this file should still exist -- neither a redirect nor an update seem suitable for it.

Are there more of these files that are deleted in the repo but still served? If so, should we get a full purge of those?

**Comment by ashawley** [comment]
I don't know if there are a lot of files like this or not.  The files on the server would need to be audited.  There may be a reason why old files are not purged.

**Comment by dwijnand** [comment]
See also https://github.com/scala/scala-lang/issues/929 which is about stale pages.  (I assume it's the same problem, maybe even the same setup.)

**Comment by ashawley** [comment]
That's about www.scala-lang.org, not docs.scala-lang.org, but yeah, same story different day.

**Comment by SethTisue** [comment]
@fsalvi can you delete this file from the server?

**Comment by ashawley** [comment]
I believe #1329 the redirect will overwrite the old file.
