### ISSUE TITLE
[glossary] unsuitable quote for return.

### ISSUE THREAD

**Issue by dongxuwang** [scala/docs.scala-lang#1369]
It should be better to make term italic rather code quote, because any other terms are using italic.
First sentence of https://docs.scala-lang.org/glossary/index.html#return
```
- A function in a Scala program `returns` a value.
+ A function in a Scala program _returns_ a value. 
```

**Comment by SethTisue** [comment]
(on something as small as this, you can just open a pull request directly, a separate issue is not needed)
