### ISSUE TITLE
compiler options page needs a refresh for 2.13

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#1381]
https://docs.scala-lang.org/overviews/compiler-options/index.html needs updating (reported by @nafg on Gitter)

the `compilerOptionsExporter` subproject in the scala/scala report semi-automates this, so someone needs to run that and then put together a PR.

volunteer?

**Comment by som-snytt** [comment]
nafg is so helpful. This is on the list at https://github.com/scala/scala/pull/7686 which became https://github.com/scala/scala/pull/7908.

The build task could use some improvement to reduce hand tweaks.

I'll try to get to it in the absence of a volunteer, but perhaps helpful nafg will take it up.

**Comment by exoego** [comment]
Opened a PR in https://github.com/scala/docs.scala-lang/pull/1435
