### ISSUE TITLE
[cheatsheet] Source code of cheatsheet should not belong to overview, as of docs's website is.

### ISSUE THREAD

**Issue by dongxuwang** [scala/docs.scala-lang#1386]
See the banner of [website](https://docs.scala-lang.org/) ,  where cheatsheet is in. In contract, see its [source code](https://github.com/scala/docs.scala-lang/edit/master/_overviews/cheatsheets/index.md), which is under the overview.

**Comment by exoego** [comment]
PR: https://github.com/scala/docs.scala-lang/pull/1460

**Comment by ashawley** [comment]
I just came across this.  Sorry, I'm not following.  You mean how the cheatsheet is missing from overviews page, and is in the menu at the top of the page?

**Comment by ashawley** [comment]
Oh, I get it.  The markdown file for the cheatsheet is in "_overviews", but the cheatsheet isn't part of the "Overviews" part of the site.

I wonder if we take a different direction. Cheatsheet is getting long.  Anybody want to try to incorporate the cheatsheet back as an overview section?  That way it can be split up in to separate pages?  

It could move out of "overviews" or stay, I guess I was more interested in it being broken up.  I've been intending to look into this, but haven't yet.  Will #1460 do this?

**Comment by exoego** [comment]
Regardess of whether cheatsheet stays in overviews or not, we can split cheatsheet into sub pages.
Splitting cheatsheet into sub-pages can be addressed separately.

Both from site structure (URL) and content, the cheatsheets are not a a sub section of overviews right now.
So PR #1460 separate cheatsheet from overviews.
I think that is more straightforward and does not cause confusing for maintainers/contributors.
