### ISSUE TITLE
Sidebar ToC misaligned if <h4> exists

### ISSUE THREAD

**Issue by exoego** [scala/docs.scala-lang#1429]
If there are `<h4>` (heading level 4 elements) in page, it is displayed with no margin with parent heading in the sidebar ToC. 

Example: https://docs.scala-lang.org/tutorials/scala-for-java-programmers.html#anonymous-functions
![image](https://user-images.githubusercontent.com/127635/61091636-de5cc600-a47d-11e9-9e56-00a95fed1f5c.png)

**Comment by dongxuwang** [comment]
This might be the browsers compatibility. It looks in an latest mac Chrome like this:

![image](https://user-images.githubusercontent.com/4261431/61197872-a8337680-a709-11e9-906a-167dfd35fc15.png)

**Comment by SethTisue** [comment]
@dongxuwang even in your screen shot, the spacing looks wrong to me (tighter than it should be)

**Comment by dongxuwang** [comment]
Yes, kind of. 
Well, I will check whether it is the jeklly's rendering problems or our css.
