### ISSUE TITLE
Style Docs Missing Arity-1 and Higher-order Functions sections

### ISSUE THREAD

**Issue by flakeparadigm** [scala/docs.scala-lang#1431]
On the style guide, the Table of contents includes an entry for Arity-1 and Higher-Order Functions under "Method invocation": https://docs.scala-lang.org/style/

However the linked page (https://docs.scala-lang.org/style/method-invocation.html) doesn't actually contain these sections.

Were they forgotten, or no longer relevant?

**Comment by SethTisue** [comment]
it's highly likely that nobody remembers what happened here

so, you or anyone interested in submitting a fix could 1) see if what happened is clear from looking at the history in version control, and 2) if it isn't, just don't worry about it, and go ahead and remove the bad entries

**Comment by flakeparadigm** [comment]
It seems to be present in [this document on codecommit.com](http://www.codecommit.com/scala-style-guide.pdf) which seems to be one of the main sources for this part of the Scala site.

I can go ahead and open a PR to add the content from there.
