### ISSUE TITLE
Compiler option page is still for Scala 2.12

### ISSUE THREAD

**Issue by exoego** [scala/docs.scala-lang#1444]
Even after PR #1435, `compiler-options.yml` still contains data for Scala 2.12.
One example is `-Xfuture`.
https://github.com/scala/docs.scala-lang/blob/8625f61f082e3a1d58ca050668d92bf2a0fdc4e1/_data/compiler-options.yml#L300-L303

[But in Scala 2.13](https://github.com/scala/scala/blob/63f89ba721034027a091663d226cd54915bac65f/src/compiler/scala/tools/nsc/settings/ScalaSettings.scala#L484-L486), `-Xfuture`'s description is `Replaced by -Xsource.`.

**Comment by exoego** [comment]
Settinc Scala compiler version to 2.13.0 via

```
$ sbt -Dstarr.version=2.13.0 generateDocsData
```

does not help.

**Comment by som-snytt** [comment]
That's a good one. I just noticed on my other PR that the sbt task is under 2.12.

**Comment by som-snytt** [comment]
The PR is automated output, with local paths edited out.
