### ISSUE TITLE
FAQ has an A referring to old collection library

### ISSUE THREAD

**Issue by Philippus** [scala/docs.scala-lang#1495]
see https://docs.scala-lang.org/tutorials/FAQ/collections.html

**Comment by khlumzeemee** [comment]
Hi @Philippus, could you be a bit more specific? Maybe a line number and an example: current value ==> expected value ?

**Comment by Philippus** [comment]
The answer is about the collection library as it was in scala 2.8. The collection library changed in scala 2.13.

**Comment by khlumzeemee** [comment]
Thank you for clarifying.
I can imagine two kinds of pull requests:
- Option 1: keep more or less the current structure, update diagrams and references, update content
**Pros**: faithful to the original
**Cons**: time consuming, review will be time consuming too, error prone

- Option 2: take a fresh start and reference blogs and/or recent official documentation which give a more up to date and official explanation.
**Pros**: content will be updated, more official documentation, less time consuming, review cycle shortened
**Cons**: we deprecate the original answer

Do you have a preference?

**Comment by khlumzeemee** [comment]
Possible new references:
https://subscription.packtpub.com/book/application_development/9781788836302/1/ch01lvl1sec13/the-scala-2-13-collection-library
https://docs.scala-lang.org/overviews/core/architecture-of-scala-213-collections.html
https://www.scala-lang.org/api/current/scala/collection/index.html

**Comment by Philippus** [comment]
Fixed in https://github.com/scala/docs.scala-lang/pull/1844.
