### ISSUE TITLE
Tutorial: The example of case classes does not work

### ISSUE THREAD

**Issue by eisemar** [scala/docs.scala-lang#1512]
The example in the section of "Case classes" in the tutorial does not work. 

The tree in the tutorial is defined as an abstract class. But my IDE (IntelliJ IDEA) could not
find Sum, Const, eval and derive in the main method.

The solution is to create an object naming it for example Expr. In the object Tree should
be defined as a trait with the methods eval and derive. Then the case classes Sum, Var and Const 
should be derive from Tree and contain the concrete implementations of the methods eval and derive. 

It should be mentioned that the main method should be in another object class. This object can be called Calc. In this class Expr should be imported (import Expr._). 

For a beginner or someone who is familiar with other programming languages the current
example code (abstract class) can be confusing because this code does not work in IntelliJ IDEA.  

Using the solution (using a trait) requires that the concept of traits is introduced. So it is recommended to swap the order of the section "Case classes" and "Trait" so the section "Trait" should be before the section "Case classes" because the working solution uses a trait.

The issue of the example in the tutorial and its solution can be found here:
https://stackoverflow.com/questions/57628249/forward-reference-extends-over-definition-value-exp-when-using-an-abstract-cla

**Comment by maseev** [comment]
I believe you're referring to this particular [section](https://docs.scala-lang.org/tutorials/scala-for-java-programmers.html#case-classes-and-pattern-matching) of the `Scala For Java Programmers` guide.

Here's a complete code example which pretty much copies every code block from the guide section you mentioned:

```scala
object Calc {

  abstract class Tree
  case class Sum(l: Tree, r: Tree) extends Tree
  case class Var(n: String) extends Tree
  case class Const(v: Int) extends Tree

  type Environment = String => Int

  def main(args: Array[String]): Unit = {
    val exp: Tree = Sum(Sum(Var("x"),Var("x")),Sum(Const(7),Var("y")))
    val env: Environment = { case "x" => 5 case "y" => 7 }
    println("Expression: " + exp)
    println("Evaluation with x=5, y=7: " + eval(exp, env))
    println("Derivative relative to x:\n " + derive(exp, "x"))
    println("Derivative relative to y:\n " + derive(exp, "y"))
  }

  def eval(t: Tree, env: Environment): Int = t match {
    case Sum(l, r) => eval(l, env) + eval(r, env)
    case Var(n)    => env(n)
    case Const(v)  => v
  }

  def derive(t: Tree, v: String): Tree = t match {
    case Sum(l, r) => Sum(derive(l, v), derive(r, v))
    case Var(n) if (v == n) => Const(1)
    case _ => Const(0)
  }
}
```

And here's a little demo which shows that IntelliJ IDEA can actually run this example:

![success](https://user-images.githubusercontent.com/3434800/66368709-80c80f00-e9c3-11e9-932e-9cbba6e71a36.gif)

Hope this helps.

**Comment by SethTisue** [comment]
closing, since we don't have any clear confirmation that an issue exists
