### ISSUE TITLE
Syntax highlighting problem for fenced code blocks

### ISSUE THREAD

**Issue by julienrf** [scala/docs.scala-lang#1538]
As shown here: https://github.com/scala/docs.scala-lang/pull/1469#pullrequestreview-295418228

**Comment by SethTisue** [comment]
someone want to look into whether this might be an easy adjustment in whatever Jekyll thing is doing the highlighting?

**Comment by ashawley** [comment]
It is called Rouge, and there is a lexer for Scala here https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/lexers/scala.rb

I believe Rouge was recently updated when Jekyll was updated in #1337.

**Comment by som-snytt** [comment]
:notes: Don't fence me in... :notes:

**Comment by bishabosha** [comment]
fixed by #2798
