### ISSUE TITLE
link to API doesn't seem to work

### ISSUE THREAD

**Issue by eriklovlie** [scala/docs.scala-lang#1587]
In [this page](https://docs.scala-lang.org/tutorials/FAQ/finding-symbols.html) the following link is used several times:

`https://www.scala-lang.org/api/current/index.html#index.index-_`

I'm not entirely sure what should be happening but at least in my browser (firefox 70.0.1 on windows) the page I'm taken to doesn't seem to do what the above page states:

> index page for identifiers not starting with letters

**Comment by chloecollins** [comment]
I have also encountered this issue, on firefox 71.0. I believe it may be a vestigial link from v2.10-2.11, when this operation was supported. e.g. [v2.10.0](https://www.scala-lang.org/api/2.10.0/index.html#index.index-_). I was unable to find a similar page in the current API docs.

This could be replaced with an instruction directing the reader to use the search bar at the top of the current API version, which would produce a url dependent on their search:
`https://www.scala-lang.org/api/current/scala/collection/index.html?search=%`

**Comment by SethTisue** [comment]
@chloecollins yes, I agree that's the right solution

**Comment by gkepka** [comment]
Completed by #1844
