### ISSUE TITLE
Link 'processing of XML data' on Introduction page points to 404

### ISSUE THREAD

**Issue by alissapaluska** [scala/docs.scala-lang#1598]
Looking over the documentation on, https://docs.scala-lang.org/tutorials/tour/tour-of-scala.html.html, and in the second paragraph under 'Scala is functional,' there's a link, **processing of XML data**, that doesn't seem to direct me to an active page but rather **Not Found**, 404. The link address: https://docs.scala-lang.org/tutorials/tour/xml-processing.html

**Comment by SethTisue** [comment]
I think the best fix here would be to omit the reference to XML entirely. At one time, a decade ago or longer, built-in XML support was one of Scala's banner features. These days, it isn't worth calling attention to, especially in such a prominent position. 

(Aside: in the same sentence, lord knows what "right-ignoring" is supposed to refer to, it doesn't mean anything to me.)

**Comment by ashawley** [comment]
Yeah, there was an attempt to remove references to XML in #743, but I guess we missed a few.

**Comment by chloecollins** [comment]
Is this still an issue? Visiting the page right now, I found this link to be directed towards https://github.com/scala/scala-xml/wiki/XML-Processing - which loads successfully.

**Comment by ashawley** [comment]
I notice the original post gives a link with two ".html" extensions.  Seems to redirect, now.  Was that the issue?

**Comment by Philippus** [comment]
I think this was fixed in https://github.com/scala/docs.scala-lang/issues/1606#issuecomment-568444771.
