### ISSUE TITLE
https://docs.scala-lang.org/tutorials deprecated?

### ISSUE THREAD

**Issue by danielgerigk** [scala/docs.scala-lang#1606]
Hey, I've noticed that the deprecated website [https://docs.scala-lang.org/tutorials](https://docs.scala-lang.org/tutorials) is still up, containing an older version of _A Tour of Scala_. (The latest version can be found at [https://docs.scala-lang.org/tour/tour-of-scala.html](https://docs.scala-lang.org/tour/tour-of-scala.html).) Is there a reason for not removing the old version?

**Comment by SethTisue** [comment]
@fsalvi perhaps the best approach here would be to remove the files but institute a redirect so that any URL for any of the old tutorial pages would redirect to the front page of the new tour?

**Comment by fsalvi** [comment]
Ok, I removed the old files and added redirects.

**Comment by SethTisue** [comment]
cool, thanks Fabien!
