### ISSUE TITLE
I got some error with the page `package object`

### ISSUE THREAD

**Issue by fooSynaptic** [scala/docs.scala-lang#1608]
I followed the tutorial of [package object](https://github.com/scala/docs.scala-lang/blob/master/_zh-cn/tour/package-objects.md)
And prepared scala scripts with follow directory format:
```
./gardening/
./gardening//fruits
./gardening//fruits/Fruit.scala
./gardening//fruits/package.scala
```
And run script `scala PrintPlanted.scala` parallize with gardening dir

but got exception as follow:
```
PrintPlanted.scala:7: error: not found: value fruits
    for (fruit <- fruits.planted) {
                  ^
PrintPlanted.scala:8: error: not found: value showFruit
      showFruit(fruit)
      ^
```

Can you help me to figure out this issue?

**Comment by SethTisue** [comment]
if you have multiple `.scala `files, the script runner (`scala Foo.scala`) no longer suffices, and you'll need to separately compile (`scalac *.scala`) and run (`scala Foo`) your code, or use a build tool or IDE which knows how to handle multiple source files.

if you have any followup questions, please use https://users.scala-lang.org (or any of the other sources of help listed at https://www.scala-lang.org/community/)

**Comment by Philippus** [comment]
After doing that, the example will still not work though. I've fixed that in https://github.com/scala/docs.scala-lang/pull/1609.

**Comment by fooSynaptic** [comment]
@Philippus @SethTisue thank for kindly support.
