### ISSUE TITLE
Scala Book table of contents appears incomplete

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#1674]
the ToC is too long to fit in the space provided, so it gets cut off, as seen here (in Safari):

<img width="836" alt="Screen Shot 2020-03-30 at 5 12 46 PM" src="https://user-images.githubusercontent.com/161079/77973754-10cb7f00-72aa-11ea-8329-66d1ba04267a.png">

or rather it _appears_ to get cut off, it _appears_ that `try/catch/finally`is the last entry, but the table is actually scrollable so you can see the rest, but it's easy to miss that there's more, and the scrolling seems unnecessary? I think it would be preferable if the full ToC was always visible

@mlachkar not sure if this is related to your recent ToC changes, or if it was like this before

**Comment by mlachkar** [comment]
It was already like that. I agree it's hard to see that you can scroll (same in tour of scala)
If we show the entire table of content, it will look like this: 
![image](https://user-images.githubusercontent.com/7843237/78003376-d3fa9900-7338-11ea-84d7-727fc1f3fbc5.png)

**Comment by SethTisue** [comment]
the long ToC does look a bit funny on that page (which has especially short content), but regardless, I think it's preferable to the scrolling

**Comment by mlachkar** [comment]
I agree. I will propose commit for that.
