### ISSUE TITLE
different versions on the example of libraryDependencies

### ISSUE THREAD

**Issue by marcelo-rosa** [scala/docs.scala-lang#1676]
Reading the page

https://docs.scala-lang.org/overviews/scala-book/sbt-scalatest-tdd.html

I saw a conflict in the proposed example in the section **Creating the build.sbt file**

```
libraryDependencies ++= Seq(
    "org.scalactic" %% "scalactic" % "3.0.8",
    "org.scalatest" %% "scalatest" % "3.0.8" % "test"
)
```
and
```
libraryDependencies ++= Seq(
    "org.scalactic" %% "scalactic" % "3.0.4",
    "org.scalatest" %% "scalatest" % "3.0.4" % "test"
)
```

I suggest unifying the presented versions so people (like me) that are learning Scala does not get confused about versions 3.0.4 and 3.0.8 in this example. Just pick one of them.

**Comment by SethTisue** [comment]
yes, a pull request correcting this would be welcome

**Comment by SethTisue** [comment]
incidentally the scalactic dependency isn't necessary, I don't think we should be recommending it to language newcomers. in the test configuration, it's a transitive dependency of scalatest. in the compile configuration, sure it's possible that someone would want to use it, but I think it's really better to recommend the standard, minimum thing which is a single dependency in the test config.

`% "test"` should be changed to `% Test`, either will work, but the latter is a little nicer

**Comment by SethTisue** [comment]
PR: https://github.com/scala/docs.scala-lang/pull/1694
