### ISSUE TITLE
Teensy weensy typo?

### ISSUE THREAD

**Issue by ohgrumble** [scala/docs.scala-lang#1680]
Hey ya'll. I'm currently using the Scala Book to try to learn Scala for my new job.

I noticed a small typo on this page: https://docs.scala-lang.org/overviews/scala-book/classes.html#basic-class-constructor

In the tip right before the header "Class constructors":

_Tip: If you use Scala to write OOP code, create your fields as var fields so you can mutate them. When you write FP code with Scala, you’ll general use case classes instead of classes like this. (More on this later.)_

I believe "general" in this context was meant to be "generally."

That's all. Thank you for maintaining this resource. I'm finding it incredibly helpful!

**Comment by Anurag870** [comment]
Created PR https://github.com/scala/docs.scala-lang/pull/1683

**Comment by Anurag870** [comment]
@SethTisue  This is merged. You can close this.

**Comment by Philippus** [comment]
closed in https://github.com/scala/docs.scala-lang/pull/1683. Thank you!
