### ISSUE TITLE
Inconsistent named arguments

### ISSUE THREAD

**Issue by dennisqi** [scala/docs.scala-lang#1704]
In section [Class](https://github.com/scala/docs.scala-lang/blob/master/_tour/classes.md) I found we have a named argument:
```
val point2 = new Point(y=2)
```

However in section [Named Arguments](https://github.com/scala/docs.scala-lang/blob/master/_tour/named-arguments.md) and [Default Parameter Values](https://github.com/scala/docs.scala-lang/blob/master/_tour/default-parameter-values.md) we have:
```
printName(first = "John", last = "Smith")  // Prints "John Smith"
```
and
```
val point1 = new Point(y = 1)
```

I suppose the `val point2 = new Point(y=2)` is the convention (no space between the argument and the value). It would be great if we can make it consistent.

**Comment by SethTisue** [comment]
fixed by #1707
