### ISSUE TITLE
Update macros doc for tree creation to use blackbox/whitebox context

### ISSUE THREAD

**Issue by nogurenn** [scala/docs.scala-lang#1710]
https://docs.scala-lang.org/overviews/reflection/symbols-trees-types.html#tree-creation-via-parse-on-toolboxes

I'm reading about reflection, and running the macros example gives the deprecation warning:
```scala
def impl(c: scala.reflect.macros.Context) = c.Expr[Unit](c.parse("println(2)"))
                                 ^
       warning: type Context in package macros is deprecated (since 2.11.0):
                use blackbox.Context or whitebox.Context instead
```

I thought it makes sense to raise this because of the existence of two different types of `Context`s.

**Comment by SethTisue** [comment]
a PR on this would be welcome

**Comment by nogurenn** [comment]
On it!
