### ISSUE TITLE
totaly beginner - run it fails

### ISSUE THREAD

**Issue by toohoo** [scala/docs.scala-lang#1712]
Hello,
sorry if it might be clear to everybody else. The "run it" in the docu fails:
"Error:scalac: Multiple 'scala-library*.jar' files (scala-library-2.12.0.jar, scala-library-2.12.10.jar) in Scala compiler classpath in Scala SDK scala-sdk-2.12.0"

Please help, 
regards

**Comment by SethTisue** [comment]
what URL is this in reference to?

**Comment by toohoo** [comment]
Hello,
thanks for your answer. Don't know exacly if I'm understanding you right.
I've come over this from the introduction on: 
https://docs.scala-lang.org/getting-started/intellij-track/getting-started-with-scala-in-intellij.html 
.. and there on section "Running it". There was a link to github but I can't find it anymore. Sorry.
But now I've found this:
docs.scala-lang/_getting-started/intellij-track/getting-started-with-scala-in-intellij.md

Thanks in advance and best regards.

**Comment by SethTisue** [comment]
> I've come over this from the introduction on:
> https://docs.scala-lang.org/getting-started/intellij-track/getting-started-with-scala-in-intellij.html

That answers my question, thanks.

The issue tracker here isn't a support forum. I suggest you ask for help in one of the venues listed at https://www.scala-lang.org/community/ . Perhaps it will turn out that our instructions should be improved. If so, please come back to this ticket with details and we'll reopen it and see what we can do.
