### ISSUE TITLE
Index of Contents not matching with next page link of "classes" page

### ISSUE THREAD

**Issue by manishbansal8843** [scala/docs.scala-lang#1726]
"next" link on page [classes ](https://docs.scala-lang.org/tour/classes.html) is pointing to [default-parameter-values](https://docs.scala-lang.org/tour/default-parameter-values.html). However, "contents" section shows that the next page should be [named-arguments](https://docs.scala-lang.org/tour/named-arguments.html). 

"contents" section indexing should be fixed.

**Comment by SethTisue** [comment]
fixed by #1727
