### ISSUE TITLE
How to get a Scala SDK on the disconnected computer?

### ISSUE THREAD

**Issue by zhaoxp0905** [scala/docs.scala-lang#1744]
I am a beginner, and I followed the tutorial of getting-started-with-scala-in-intellij.md
At step 5 of "Creating the Project", I can't get any Scala SDK, maybe because my work computer cannot connect to the Internet, I think many companies do so. How can I go on?
Thank you!

**Comment by SethTisue** [comment]
a good place to ask questions is https://users.scala-lang.org, and/or see https://www.scala-lang.org/community/ for other options
