### ISSUE TITLE
getting started with IntelliJ IDE is out of sync

### ISSUE THREAD

**Issue by macginitie** [scala/docs.scala-lang#1763]
I tried to fix part of the mismatch here:
https://github.com/scala/docs.scala-lang/compare/master...macginitie:patch-1

**Comment by macginitie** [comment]
also https://github.com/scala/docs.scala-lang/compare/master...macginitie:patch-2

**Comment by SethTisue** [comment]
would you like to submit those changes as a pull request?

**Comment by macginitie** [comment]
sure, I'm new here & didn't want to submit a PR without at least someone looking at it. I'll submit them, thanks

**Comment by gkepka** [comment]
Completed by #1773 and #1774
