### ISSUE TITLE
sbt prompts but does not accept input

### ISSUE THREAD

**Issue by macginitie** [scala/docs.scala-lang#1764]
In the getting-started-with-sbt commandline markdown file:

1. cd to an empty folder.
2. Run the following command 'sbt new scala/hello-world.g8'. This pulls the 'hello-world' template from GitHub. It will also create a target folder, which you can ignore.
3. When prompted, name the application hello-world. This will create a project called "hello-world".

at step 3, the terminal (in Windows) is not accepting any input from the keyboard, so I can't proceed. Something about the cause and/or resolution to this problem should be added to the instructions, perhaps?

**Comment by SethTisue** [comment]
is there anything in https://github.com/sbt/sbt/issues ? the issue doesn't sound familiar offhand

**Comment by macginitie** [comment]
perhaps #5063, which has this comment:
"Just posting for someone who is looking for a workaround until this gets fixed.
sbt --supershell=false new scala/scala-seed.g8"

**Comment by SethTisue** [comment]
does the workaround work for you?

**Comment by macginitie** [comment]
yes, it did

**Comment by Philippus** [comment]
According to the ticket that was mentioned, with newer sbt versions (both 1.3.x and 1.4.x releases) this is fixed and the workaround should no longer be needed.
