### ISSUE TITLE
SIP Google Doc suggestion spam

### ISSUE THREAD

**Issue by mister-walter** [scala/docs.scala-lang#1795]
I came across the ["Type Dynamic" SIP](https://docs.scala-lang.org/sips/type-dynamic.html) in the process of doing some research, and because the embedded viewer was small I opened the document in Google Docs via [the provided link](https://docs.google.com/document/d/1XaNgZ06AR7bXJA9-jHrAiBVUwqReqG4-av6beoLaf3U/edit) on that page.

The Google Doc viewer opened up in "suggestion"/"editing" mode and I found a bunch of spam suggestions on the first page. There were some helpful but old comments from 2012 further down in the doc, but as far as I can tell no other suggestions.

Here's a screenshot of the doc:
![sip-spam_000](https://user-images.githubusercontent.com/1879137/95534830-d65b4100-09b4-11eb-9a06-0655c405560b.png)

Just wanted to make y'all aware of this. Luckily the suggestions are not visible from the integrated viewer on the Scala docs website, but it was a little jarring to see nonetheless.

**Comment by sjrd** [comment]
Thank you for the report! I don't know who is the owner of that Google Doc and could fix this :s

@odersky was it you (since you're listed as author of the SIP)?

**Comment by odersky** [comment]
I have restored the document and disabled the comment option

**Comment by NthPortal** [comment]
Thanks @mister-walter!
