### ISSUE TITLE
Malformed markdown link in scaladoc/for-library-authors.md

### ISSUE THREAD

**Issue by IowU** [scala/docs.scala-lang#1810]
In the [More details on writing Scaladoc](https://github.com/scala/docs.scala-lang/blob/master/_overviews/scaladoc/for-library-authors.md#more-details-on-writing-scaladoc) there is a broken markdown. Is it supposed to point to [https://docs.scala-lang.org/style/scaladoc.html](https://docs.scala-lang.org/style/scaladoc.html)?

**Comment by SethTisue** [comment]
Is it broken? At https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html , the link works
