### ISSUE TITLE
in docs.scala-lang/_tour/variances.md variances covariance missing [+A] mark

### ISSUE THREAD

**Issue by atovk** [scala/docs.scala-lang#1824]
Consider this simple class structure:

```scala
abstract class Animal {
  def name: String
}
case class Cat(name: String) extends Animal
case class Dog(name: String) extends Animal
```

maybe change to : 

```scala

abstract class Animal[+A] {
  def name: String
}
case class Cat(name: String) extends Animal
case class Dog(name: String) extends Animal

```

?

**Comment by atovk** [comment]
If this is a problem, I can modify it.

**Comment by atovk** [comment]
[variances.covariance](https://github.com/scala/docs.scala-lang/blob/master/_tour/variances.md#covariance)

**Comment by martijnhoekstra** [comment]
The example is correct, Animal doesn't have a type parameter. In the example, using the subtypes of Animal is used to show variance of the type parameterized over Animal, not variance of Animal itself.
