### ISSUE TITLE
Language Tour Currying section could use hyperlink to Implicit Parameters

### ISSUE THREAD

**Issue by ilknarf** [scala/docs.scala-lang#1831]
[The multiple parameter lists section](https://github.com/scala/docs.scala-lang/blob/master/_tour/multiple-parameter-lists.md) contains a brief mention of implicit parameters with limited context. (Maybe it could be removed, too?) It would be helpful if it referenced https://docs.scala-lang.org/tour/implicit-parameters.html, which is placed several sections later in the tour.

**Comment by SethTisue** [comment]
yes please, PR welcome!

**Comment by flomebul** [comment]
Look like to be solved by #1684 ?

**Comment by SethTisue** [comment]
Indeed! Thanks for noticing/reporting.
