### ISSUE TITLE
Wrong type hierarchy in Variance chapter (Book extends CartItem)

### ISSUE THREAD

**Issue by MatthiasKurt** [scala/docs.scala-lang#1877]
Hello,
thanks for this good book.
i believe that in chapter about variance the type hierarchy of the example has a mistake.
In the example `Book extends CartItem` (which is not mentioned in this chapter).
I think you wanted that `Book extends Buyable`.
In the subchapter about Invariant Types you wrote:
`Book <: Buyable <: Item`
Happy new year
  Matthias

**Comment by b-studios** [comment]
Thanks, you are right!
