### ISSUE TITLE
Spelling of 'deprecated' is incorrect

### ISSUE THREAD

**Issue by jonkeatley** [scala/docs.scala-lang#1919]
In the Scala 3 scaladocs, the word 'deprecated' is spelled as 'deprectated'.

**Comment by Philippus** [comment]
Thank you for reporting it, the Scala 3 scaladocs are generated from the code in this repository: https://github.com/lampepfl/dotty. I've created a Pull Request there to fix it.

**Comment by jonkeatley** [comment]
Thanks! That was fast.
