### ISSUE TITLE
Better utilize wide (desktop) screens

### ISSUE THREAD

**Issue by rpridemore** [scala/docs.scala-lang#1933]
I find the documentation frustrating to read on my hi-res desktop screen.  The width of the main content is unnecessarily narrow, causing horizontal scrollbars to appear in code fragments.  I don't understand enough about sass to submit a PR, but I have been manually changing max-width on .wrap style from 1000px to 1500, as you can see in the attached screenshots.
![Screenshot from 2021-02-24 11-30-00](https://user-images.githubusercontent.com/11162648/109032812-04a39980-7694-11eb-9d76-c553550c1d2c.png)
![Screenshot from 2021-02-24 11-28-50](https://user-images.githubusercontent.com/11162648/109032874-1422e280-7694-11eb-8824-48156f2a2c1b.png)

Please consider widening, at least for large monitors!

**Comment by rysh** [comment]
Hi @SethTisue ,
I thought I'd give it a try, but when I checked, it seemed to have already been resolved.
<img width="1748" alt="スクリーンショット 2021-11-24 8 38 17" src="https://user-images.githubusercontent.com/828709/143145777-49caaf47-17cd-4e75-a454-40516e97a173.png">

**Comment by SethTisue** [comment]
great! thanks for checking on it
