### ISSUE TITLE
Non leaf menu entries have a blank content section

### ISSUE THREAD

**Issue by robstoll** [scala/docs.scala-lang#1959]
Navigazte to https://dotty.epfl.ch/docs/Metaprogramming/index.html

At least on Chrome mobile I see only a blank content section. I.e I see the menu, the breadcrumb  but no content. Same same if I switch to the desktop view

**Comment by SethTisue** [comment]
@b-studios is this worth addressing or should we just figure the problem might go away at the time the Dotty site is merged onto docs.scala-lang?

**Comment by SethTisue** [comment]
@robstoll does the problem still exist in the page's new location on docs.scala-lang.org?

**Comment by robstoll** [comment]
@SethTisue looks good https://docs.scala-lang.org/scala3/reference/metaprogramming.html

**Comment by robstoll** [comment]
@SethTisue as side notice, https://dotty.epfl.ch/docs/Metaprogramming/index.html still exists (with the bug), maybe time to take that one down?

**Comment by SethTisue** [comment]
Non-blank pages, at least, have a "The content of this page is outdated. Click here to find the up to date version of this page." header on them. (I'm not sure why it was decided to do that instead of just redirecting, I wasn't involved with that.)
