### ISSUE TITLE
sbt: scala 3 cannot be compiled without plugins.sbt  ch.epfl.lamp

### ISSUE THREAD

**Issue by xhudik** [scala/docs.scala-lang#1960]
Hi there, I went through: 
https://docs.scala-lang.org/scala3/book/scala-tools.html and the first exmaple with `sbt run` didnt work:
```
[info] Updated file /home/tomas/now/scala/yy/project/build.properties: set sbt.version to 1.4.7
[info] welcome to sbt 1.4.7 (Oracle Corporation Java 1.8.0_281)
[info] loading global plugins from /home/tomas/.sbt/1.0/plugins
[info] loading project definition from /home/ttt/project
[info] loading settings for project yy from build.sbt ...
[info] set current project to yy (in build file:/home/tt/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-library:3.0.0-RC1
[error]   Not found
[error]   Not found
[error]   not found: /home/tt/.ivy2/localorg.scala-lang/scala-library/3.0.0-RC1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala-library/3.0.0-RC1/scala-library-3.0.0-RC1.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
```

It works but only if you add:
```
project/plugins.sbt 
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.5.3")
```
Question: will this plugin be needed once Scala 3 is officially released?
If yes, it should be added to the text
If no, some note about it should be added for readers before the official release

**Comment by SethTisue** [comment]
> will this plugin be needed once Scala 3 is officially released?

It won't be needed once sbt 1.5 is released. If you use sbt 1.5.0-M2, you don't need sbt-dotty. But 1.5.0-M2 is just a milestone, so you might consider it a bit risky to early-adopt.

**Comment by SethTisue** [comment]
(As for updating the doc, yes, agree. I mainly work on Scala 2, perhaps someone else reading this repo would like to make the change, perhaps @alvinj or @b-studios?)

**Comment by eed3si9n** [comment]
Not sure if you're ready for Scala 3 if you think 1.5.0-M2 is too risqué for work.

**Comment by xhudik** [comment]
Actually, I just found out the page already contains a comment `{% comment %}` about it - maybe it should be put as a note/normal text. `{% comment %}`  is invisible for a normal user

**Comment by alvinj** [comment]
>  I just found out the page already contains a comment

Yes, I think we had an offline discussion about how to handle this. I think we thought the need was going away soon, and that’s how that became a comment. If you want to remove that comment, that’s fine by me. I’ll set a reminder for every month to then update this page when sbt 1.5.0 is released.

**Comment by SethTisue** [comment]
sbt 1.5.0 is out now and doesn't require sbt-dotty

**Comment by xhudik** [comment]
ok, thanks. I think we can close this issue!
