### ISSUE TITLE
Site isn't being published

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#1979]
I noticed just now that https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html is out of date w/r/t to https://github.com/scala/docs.scala-lang/blob/main/_overviews/jdk-compatibility/overview.md

is the site not publishing? (maybe because of the change from `master` to `main`?)

**Comment by SethTisue** [comment]
@fsalvi can I ask you to look into this...?

**Comment by fsalvi** [comment]
I started manually the build, it should be ok now.
It seems one setting was missing to use main instead of master. Sorry about that.
I will follow the next builds to ensure it's ok.

**Comment by SethTisue** [comment]
excellent, thank you!
