### ISSUE TITLE
JDK compatibility page should cover Graal Native Image

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#1982]
https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

even a small amount of wording, and a link to https://github.com/scalameta/sbt-native-image and anything else important, would be way better than nothing

if the amount of information we have grew enough it could become its own page, but I think adding something to the existing page would be a good start

**Comment by SethTisue** [comment]
another thing to link to would be https://github.com/scala/bug/labels/graal — there are open tickets and some closed ones too

**Comment by chaitanyawaikar** [comment]
I can pick this up

**Comment by chaitanyawaikar** [comment]
PR created https://github.com/scala/docs.scala-lang/pull/1989.
Looking forward to your valuable feedback. Thanks !!
