### ISSUE TITLE
Documentation to take advantage of larger screens

### ISSUE THREAD

**Issue by fernandoracca** [scala/docs.scala-lang#2028]
When reading on reasonably large screens, particularly 4K monitors, the main area for content is really small, and there's huge amount of wasted empty space.

This selector changes a single property which expands to fill the screen, which makes a large difference. 

```javascript
document.querySelectorAll(“.wrap").forEach ( el => el.style.maxWidth = "2048px" )
```

Consider including such support directly on the website.

**Comment by fernandoracca** [comment]
I actually have a PR ready. It's tested on both my laptop's monitor and an external 27" 4K monitor, and it fills up the space nicely.

**Comment by b-studios** [comment]
I agree that the docs benefit from this change:

![image](https://user-images.githubusercontent.com/408265/118983847-2653aa80-b97d-11eb-80bd-9f4ea2673c07.png)


However, the landing page really is not designed with this in mind:

![image](https://user-images.githubusercontent.com/408265/118983899-39ff1100-b97d-11eb-9df5-ba8279fe0c52.png)

**Comment by fernandoracca** [comment]
Thanks for the feedback @b-studios .
I'll look into it tonight, to see if i can also improve that page. I'm not much of a CSS person, so i can't promise a substantial change. 
If you have any suggestion of how to structure it, please do let me know.

**Comment by gkepka** [comment]
Completed by #2030
