### ISSUE TITLE
FAQ redirects not working

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#2065]
so for example https://docs.scala-lang.org/tutorials/FAQ/breakout.html still exists, even though the source file for it was removed by 836fa133b704ecff127dcf3eeca5f1c63c276ebe

`_overviews/FAQ/index.md` has

```
redirect_from: "/tutorials/FAQ/breakout.html"
redirect_from: "/tutorials/FAQ/chaining-implicits.html"
redirect_from: "/tutorials/FAQ/collections.html"
redirect_from: "/tutorials/FAQ/context-bounds.html"
redirect_from: "/tutorials/FAQ/finding-implicits.html"
redirect_from: "/tutorials/FAQ/finding-symbols.html"
redirect_from: "/tutorials/FAQ/stream-view.html"
redirect_from: "/tutorials/FAQ/yield.html"
```

but the redirect isn't functioning as expected.

so there are actually two problems here:

1) removed pages should no longer be online. @fsalvi is this something you can clean out...?
2) the redirect isn't working and I don't understand why. @fsalvi do you have any insight into this? if not, I can try and dig into it

**Comment by fsalvi** [comment]
I fixed the 1st point.

For the 2nd point, I did some tests and only the last item in the redirect_from list is generated (in your case, yield.html). I wonder why... There's no error nor warning in the output, even with the verbose mode.

**Comment by fsalvi** [comment]
BTW, using this syntax solves the problem:

redirect_from: 
  - "/tutorials/FAQ/breakout.html"
  - "/tutorials/FAQ/chaining-implicits.html"
  - "/tutorials/FAQ/collections.html"
  - "/tutorials/FAQ/context-bounds.html"
  - "/tutorials/FAQ/finding-implicits.html"
  - "/tutorials/FAQ/finding-symbols.html"
  - "/tutorials/FAQ/yield.html"
  - "/tutorials/FAQ/stream-view.html"

**Comment by Philippus** [comment]
I think the syntax used here is for a single url and every redirect_from in the list overrides the previous one. To have a list you need a different way of putting them (https://github.com/jekyll/jekyll-redirect-from#usage).

**Comment by fsalvi** [comment]
The same syntax error is also in other files, eg _tour/named-arguments.md

**Comment by Philippus** [comment]
I'll make some changes for those.
