### ISSUE TITLE
Missing step in getting started with Scala 3

### ISSUE THREAD

**Issue by jacobus** [scala/docs.scala-lang#2092]
The[ Getting Started with Scala 3 page](https://www.scala-lang.org/download/scala3.html) does not say how to run a Scala 3 program after installing with coursier. Step 3 "Use Scala" only shows how to load a file into the REPL and how to compile a file, but no mention of running it.

**Comment by bishabosha** [comment]
related https://github.com/coursier/coursier/issues/2058

**Comment by gkepka** [comment]
No longer relevant: the [Getting Started](https://docs.scala-lang.org/getting-started/install-scala.html) page explains all the steps needed to run a Scala 3 program.
