### ISSUE TITLE
Control Structures- Description does not match function's signature

### ISSUE THREAD

**Issue by Altair-Bueno** [scala/docs.scala-lang#2097]
On [Control Structures - Using a `match` expression as the body of a method](https://github.com/scala/docs.scala-lang/blob/main/_overviews/scala3-book/control-structures.md#using-a-match-expression-as-the-body-of-a-method):

>Because `match` expressions return a value, they can be used as the body of a method.
>This method takes a `Boolean` value as an input parameter, and returns a `String`, based on the result of the `match` expression:
>
>```scala
>def isTruthy(a: Matchable) = a match
>  case 0 | "" => false
>  case _ => true
>```

This method does not only take Boolean as an input, as stated by the function signature. It should work with any `Matchable` value. Also, it does not contain the `case false` neither the `case null` scenario. I'm not sure if it is intended this way or it is an error. I imagine this function tries to mimic JavaScript's behaviour so it should consider those cases too. I added some spaces to ident the `true` case as it is usually done in other other FP languages like Haskell.  I'm not familiar enough with Scala, let me know if my changes are OK and i'll create a pull request

#### Proposed solution

Because `match` expressions return a value, they can be used as the body of a method.
This method takes a `Matchable` value as an input parameter, and returns a `Boolean`, based on the result of the `match` expression:

```scala
def isTruthy(a: Matchable) = a match
  case 0 | "" | false | null => false
  case _                     => true
```

The input parameter `a` is defined to be the [`Matchable` type][matchable]---which is the root of all Scala types that pattern matching can be performed on.
The method is implemented by matching on the input, providing two cases:
The first one checks whether the given value is either the integer `0`,  an empty string, `null` or `false` and returns `false` in this case.
In the default case, we return `true` for any other value.
These examples show how this method works:

```scala
isTruthy(0)      // false
isTruthy(false)  // false
isTruthy(null)   // false
isTruthy("")     // false
isTruthy(1)      // true
isTruthy(" ")    // true
isTruthy(2F)     // true
```

Using a `match` expression as the body of a method is a very common use.

**Comment by Altair-Bueno** [comment]
Quick note: `isTruthy` appears [here too](https://github.com/scala/docs.scala-lang/blob/main/_overviews/scala3-book/methods-most.md#using-if-as-a-method-body). Apparently, this function refers to Perl's definition of truthy. Sadly, i'm not familiar with Perl

**Comment by SethTisue** [comment]
yes, a PR on this would be welcome

**Comment by Altair-Bueno** [comment]
I created a [PR](https://github.com/scala/docs.scala-lang/pull/2154) using Perl's definition of `truthy` as seen [here](https://github.com/scala/docs.scala-lang/blob/main/_overviews/scala3-book/methods-most.md#using-if-as-a-method-body) to keep things related
