### ISSUE TITLE
ClassManifest is deprecated

### ISSUE THREAD

**Issue by xuwei-k** [scala/docs.scala-lang#210]
We should replace to `ClassTag`

http://docs.scala-lang.org/overviews/collections/arrays.html
http://docs.scala-lang.org/tutorials/FAQ/context-and-view-bounds.html
http://docs.scala-lang.org/overviews/collections/concrete-mutable-collection-classes.html

http://docs.scala-lang.org/ja/overviews/collections/concrete-mutable-collection-classes.html
http://docs.scala-lang.org/ja/overviews/collections/arrays.html

**Comment by jarrodwb** [comment]
Was this fixed by #570 ?

**Comment by SethTisue** [comment]
#570 only fixed one of the things on @xuwei-k's list

**Comment by jiminhsieh** [comment]
@SethTisue Is anyone could help on this one? Since this year of _Open Source Spree_ has already passed. By the way, there is a question about gitignore which is ignoring `scala.github.com/_site`. I could not figure out the reason. Thanks!

**Comment by SethTisue** [comment]
@jiminhsieh yes, please!

`_site` is in `.gitignore` because it contains build products

from http://jekyllrb.com/docs/structure/ :

<img width="683" alt="screen shot 2017-07-20 at 8 19 23 am" src="https://user-images.githubusercontent.com/161079/28416951-2b0b3a9c-6d24-11e7-83b3-cc6f0630eb05.png">
