### ISSUE TITLE
Bug in example code of "Scala 3: Scala for Python Developers"

### ISSUE THREAD

**Issue by gverbruggen** [scala/docs.scala-lang#2113]
Near the bottom of the document there's this example:

**Filtering:**
```python
# Python
f = lambda x: x if x > 1 else 1 
x = filter(f, numbers)
```
```scala
// Scala
val x = numbers.filter(_ > 1)
```

That first line of Python is wrong.

The correct python for the filter is:
```python
f = lambda x: x > 1
x = filter(f, numbers)
```

And if you want to more closely mirror the Scala example:
```python
x = tuple(filter(lambda x: x > 1, numbers))
```

**Comment by julienrf** [comment]
Thank you for reporting! Would you be interested in submitting a fix?

**Comment by sthagen** [comment]
The python code may be correct that way, but in my experience not idiomatic. You try to not name lamdas anyway in python, as in most such cases a plain old function then serves you better.

The final example in the issue description using filter I would expect rather written like this:
```python
x = tuple(n for n in numbers if n > 1)
```
