### ISSUE TITLE
No Search 

### ISSUE THREAD

**Issue by vee-k** [scala/docs.scala-lang#2175]
Hi, just started learning Scala3, love the book, but couldn't find Search function - is there a way to search through the book?

**Comment by julienrf** [comment]
Hi @vee-k, there is currently a search function, but it is available on the landing page only (https://docs.scala-lang.org). I agree that we should make it available on every page.

If someone is interested in making this change, a pull request would be welcome :relaxed:

**Comment by vee-k** [comment]
Ah, great, thank you for the heads-up!
 I'm blind ... 
But it would be a bit more practical to have it on each page :)

Thanks a lot for putting the whole thing up anyway !
Have a nice weekend ahead 


On September 10, 2021 7:41:22 AM UTC, Julien Richard-Foy ***@***.***> wrote:
>>> Hi @vee-k, there is currently a search function, but it is available on the landing page only (https://docs.scala-lang.org). I agree that we should make it available on every page.
>>> 
>>> If someone is interested in making this change, a pull request would be welcome :relaxed: 
>>> 
>>> -- 
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/scala/docs.scala-lang/issues/2175#issuecomment-916700552

Viktoriana Kostov
Visual Communication Designer
komiska.com
***@***.***

**Comment by gkepka** [comment]
Completed by #2201
