### ISSUE TITLE
if/then/else, for, and old syntax

### ISSUE THREAD

**Issue by erdnaxeli** [scala/docs.scala-lang#2216]
Hi,

[This page](https://docs.scala-lang.org/scala3/book/taste-control-structures.html) talks about control structures. For the if/then/else it only expose the (new ?) syntax 
```scala
if a < b then
  something
else
  something_else
```

But for the `for` or the `while` construct, it also show the old syntax with parenthesis around the condition and curly brackets. Isn't it a bit confusing? Should not the doc either:
* present the old syntax for the if/then/else too
* or present only the new syntax for all construct (my preferred solution)?

**Comment by SethTisue** [comment]
> present the old syntax for the if/then/else too

agree

**Comment by alvinj** [comment]
I just looked at this bug and that page, and if I understand it right, I think this has been completed as part of #2481, and can be closed?

**Comment by erdnaxeli** [comment]
I think you're right.
