### ISSUE TITLE
Scala 3 for python developers: switch/match/case

### ISSUE THREAD

**Issue by j123b567** [scala/docs.scala-lang#2232]
From python 3.10 (see [PEP 634](https://www.python.org/dev/peps/pep-0634/)) there is already structural pattern matching.

So comparision of "match expressions:" and "switch/match:" is probably no longer "N/A" for python.

I'm not using python >=3.10 nor scala so I'm not able to suggest proper python alternative.

**Comment by byyue** [comment]
Thanks. I'll submit a PR.
