### ISSUE TITLE
Possible contradiction: Minor version bump indicates binary incompatibility

### ISSUE THREAD

**Issue by scharom16** [scala/docs.scala-lang#2238]
The following line does state that there is a binary incompatibility when upgrading the minor version.
https://github.com/scala/docs.scala-lang/blob/bcd9506ad3e6b8ba6036a5c361525ed530d76212/_overviews/tutorials/binary-compatibility-for-library-authors.md?plain=1#L203

A few lines above, the three rules on semantic versioning state that a minor version bump should be used when the publisher introduces a source code incompatibility and not a binary incompatibility.

As a novice, I am confused. Please correct me if the Error is on my side. :)

**Comment by sjrd** [comment]
For v0.x.y versions, the rules are different than for >= v1.0.0. A change in `x` can break binary compatibility.

**Comment by scharom16** [comment]
Ahh, thank you for the clarification.
