### ISSUE TITLE
/api/current/ leads to Scala 2 API docs instead of Scala 3

### ISSUE THREAD

**Issue by Nicolapps** [scala/docs.scala-lang#2270]
Hello,

The https://www.scala-lang.org/api/current/ URL currently shows documentation for the latest Scala 2 version. I would expect it to lead to https://www.scala-lang.org/api/3.x/ instead. Is the current behavior expected?

**Comment by julienrf** [comment]
This is a good point. We clearly have _two_ current stable versions, as shown on the home page:

![Screenshot from 2021-12-09 08-55-42](https://user-images.githubusercontent.com/332812/145356305-6a759841-6a05-4260-86aa-50f9245e4422.png)

Eventually, we want `current` to be `3.x`, but I am not sure _now_ is the right time to do so.

**Comment by Nicolapps** [comment]
Thank you for your reply. I will use `3.x` in the mean time.

**Comment by gkepka** [comment]
https://www.scala-lang.org/api/current/ does lead to Scala 3 API docs now.
