### ISSUE TITLE
domain-modelling-tools: Use `name` argument in abstract class

### ISSUE THREAD

**Issue by arkivm** [scala/docs.scala-lang#2278]
In Scala 3 Book, under [Abstract classes](https://docs.scala-lang.org/scala3/book/domain-modeling-tools.html#abstract-classes), the example for an abstract class that can take arguments doesn't really use the argument.

```scala
abstract class Pet(name: String):
  def greeting: String
  def age: Int
  override def toString = s"I say $greeting, and I’m $age"
```

However, the immediate example that shows "traits with parameters" use them.

I'd be happy to send a PR.

**Comment by Philippus** [comment]
That would be great @arkivm !
