### ISSUE TITLE
Anchor points ⚓

### ISSUE THREAD

**Issue by ShalokShalom** [scala/docs.scala-lang#2299]
I like to link that section specifically:

![Screenshot_2022-01-27-09-18-41-22](https://user-images.githubusercontent.com/6344099/151319342-14c31a79-54c5-4d18-a5fc-3584aa95cfdf.jpg)

That is currently not possible.
I can only link the [whole page](https://docs.scala-lang.org/scala3/book/scala-features.html), and the recipient has to scroll down to that section.

Other documentation pages offer the ability to click the header, or a symbol next to it, and link the section specifically.

I ask to implement that.

Thanks a ton

**Comment by byyue** [comment]
Do you mean [this](https://docs.scala-lang.org/scala3/book/scala-features.html#expressive-type-system)?

**Comment by ShalokShalom** [comment]
Yep. How you are doing this?

**Comment by byyue** [comment]
Please refer to the [anchor within a page](https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html). 

Then you can review the source code and generate the link: `https://{the_link_to_the_page}#{some_id_or_name}`

**Comment by ShalokShalom** [comment]
You surely agree, it's more preferable to simply have an icon, that you can right-click.

**Comment by gkepka** [comment]
Completed by #2852
