### ISSUE TITLE
Questionable terminology

### ISSUE THREAD

**Issue by ac2epsilon** [scala/docs.scala-lang#2346]
Here and there I see "generic (type) parameters", so I feel like we have got "generic parameters", type parameters, which in turn also generics (which is perfectly possible, but probably not what we are trying to express). Well, if I am mistaken not: There are Generics || Generic Types (classes, traits in Scala, interfaces in Java, methods, functions, etc) which have/use/declared-with Type Parameters (also known as diamond/bracket ones). 1. Generics are 2. Parametrized with 3. Type(s). Right? While syntactically acceptable, the phrase "generic type parameters" sounds like the wrong combination of words. If this point is considered as worth attention I will (lazily) replace "generic type parameters" with "generic types" or "type parameters", or something more appropriate.

**Comment by julienrf** [comment]
Good point, I agree with replacing “generic type parameters” with “type parameters”.
