### ISSUE TITLE
Placeholder FAQ claim overreaches

### ISSUE THREAD

**Issue by som-snytt** [scala/docs.scala-lang#2381]
## Reproduction steps

```scala
scala 2.13.8> List(42).flatMap(List(_ + 1))
                                    ^
              error: missing parameter type for expanded function ((<x$1: error>) => x$1.$plus(1))

scala 2.13.8> List(42).flatMap(List apply _ + 1)
val res1: List[Int] = List(43)
```

## Problem

The [FAQ](https://docs.scala-lang.org/tutorials/FAQ/index.html#why-doesnt-my-function-literal-with-_-in-it-work) claims the function can't be written with placeholder syntax.

**Comment by som-snytt** [comment]
It's place holder syntax, where it's translated to `x => expr(x)`.

I remember when I first saw someone point out how infix enables extra underscore powers. It seems magical at first, but is just ordinary syntax. Precedence rules matter in this example.

**Comment by SethTisue** [comment]
> It's place holder syntax, where it's translated 

Oops, I thought I'd removed that sentence, after Dale set me straight. I've strikethroughed it.

**Comment by som-snytt** [comment]
Taxi drivers are on strikethru, so let me know if you need a ride from the airport.

**Comment by som-snytt** [comment]
FAQ is for brevity. That's why we call it FAQ for short.
