### ISSUE TITLE
scala3 doc pages layout is broken

### ISSUE THREAD

**Issue by unkarjedy** [scala/docs.scala-lang#2398]
https://docs.scala-lang.org/scala3/guides/migration/options-new.html 

![image](https://user-images.githubusercontent.com/3989292/168741696-84a4ac70-fc3b-4f83-8f79-bb4b4dd62b4b.png)

**Comment by bishabosha** [comment]
fixed by https://github.com/scala/docs.scala-lang/pull/2397
