### ISSUE TITLE
Ordering of Guides is suboptimal

### ISSUE THREAD

**Issue by dcsobral** [scala/docs.scala-lang#24]
The first guide listed is the architecture of Scala collections. The overview of Scala collections appears further down (and with its full index -- that's bad too). People will naturally try the first resource they find, and they assume topics further up are more entry-level than topics further down.

**Comment by SethTisue** [comment]
I don't how what the order was in 2011, but the ordering at https://docs.scala-lang.org/overviews/index.html in 2018 looks decent to me
