### ISSUE TITLE
scalafiddle.io down?

### ISSUE THREAD

**Issue by eugenevankampen** [scala/docs.scala-lang#2417]
In the Basics tour there is a reference to https://scalafiddle.io. This website - today - returns a Error 522. Not sure if I should log it here as an issue. If not, please ignore.
![image](https://user-images.githubusercontent.com/106658852/171847453-72fd9308-dfa2-48d7-80bb-8ce69218f74a.png)

**Comment by slee500** [comment]
Same for me, I raised a PR to remove references to it. See https://github.com/scala/docs.scala-lang/pull/2446

![image](https://user-images.githubusercontent.com/14228817/175500945-c9b53151-748f-4923-ad32-5f9b498684b8.png)
