### ISSUE TITLE
update `futures.md` for other languages

### ISSUE THREAD

**Issue by xuwei-k** [scala/docs.scala-lang#2449]
- I think we should apply https://github.com/scala/docs.scala-lang/pull/1051 and some other changes

https://github.com/scala/docs.scala-lang/commits/main/_overviews/core/futures.md

<hr />

- [x] ja: https://github.com/scala/docs.scala-lang/blob/6d9b262389ac51/_ja/overviews/core/futures.md
- [x] _zh-cn: https://github.com/scala/docs.scala-lang/blob/6d9b262389ac51/_zh-cn/overviews/core/futures.md

**Comment by benluo** [comment]
latest translation has been PRed. Please check in PR.

**Comment by benluo** [comment]
update Chinese translation according to latest English version, see [PR #2678](https://github.com/scala/docs.scala-lang/pull/2678).
