### ISSUE TITLE
Remove Scala Actors Migration Guide/Deprecate Page

### ISSUE THREAD

**Issue by Khalian** [scala/docs.scala-lang#2542]
Akka has recently changed its licensing terms in https://github.com/akka/akka/pull/31561 and as a result https://docs.scala-lang.org/overviews/core/actors-migration-guide.html should not be encouraged since licensing is now an issue and the resulting code wont be Open Source by default. 

Two possible suggestions

1. Put a deprecation warning with the Akka License change documentation https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka as reason

2. Removing that document entirely, since its version 2.11 and above have no dependencies on Akka and scala actors have been a non factor too. 

Thoughts? I can submit a PR either way.

**Comment by julienrf** [comment]
I prefer keeping the page in case it is still useful to someone. It does not hurt, it’s already at the very bottom of the guides page.

I am happy with the solution of adding a note regarding the current license of Akka (even though that does not really apply to the version of Akka used in the migration guide).

**Comment by Khalian** [comment]
@julienrf Understood. I can put a note in there. Thanks.

**Comment by SethTisue** [comment]
I'd have been fine with just removing it, but if we're keeping it, then yes, adding notes or other adjustments that would make the current situation clear to current readers SGTM

**Comment by strelec** [comment]
This docs page looks so outdated it serves nobody, only to confuse.

A simple removal is the best option.

**Comment by julienrf** [comment]
I am fine with removing, in that case.

**Comment by Khalian** [comment]
Hey so I made the change in https://github.com/scala/docs.scala-lang/pull/2604 and deleted the actor migration guide. I presume at some point it would be picked up and reflected in the main scala docs website and we can close this?

**Comment by julienrf** [comment]
I agree to close this issue. Your changes have been published, as you can see here: https://docs.scala-lang.org/overviews/core/actors.html, and here: https://docs.scala-lang.org/overviews/index.html

However, for some reason the deleted page https://docs.scala-lang.org/overviews/core/actors-migration-guide.html is still here. It seems that the script that pulls the new website content does not remove deleted pages. I will open a separate issue to track that.

**Comment by julienrf** [comment]
Thank you for you help @Khalian!

**Comment by strelec** [comment]
Thanks!

Moreover, is there a reason that we are keeping the main Actors page?

https://docs.scala-lang.org/overviews/core/actors.html

I think there is a value of removing stuff that could potentially confuse new users. There are possibly more pages like this one that shall be removed.

**Comment by SethTisue** [comment]
I think the main Actors page should be removed, too.

**Comment by julienrf** [comment]
@strelec there is no reason for keeping it, it is still here just because nobody took the time to remove them properly. Would you be interested in helping?

**Comment by Khalian** [comment]
@julienrf Looks relatively straightforward. I can take it out.
