### ISSUE TITLE
Is the documentation about the "-release" compiler flag correct?

### ISSUE THREAD

**Issue by dalbani** [scala/docs.scala-lang#2569]
From https://docs.scala-lang.org/overviews/compiler-options/index.html#targeting-a-version-of-the-jvm:
> ### Targeting a version of the JVM
> Applications or libraries targeting the JVM may wish to specify a target version.
>
> The `-release `option specifies the target version, such as “8” or ___**“18”**___.

But, on the other hand, from https://docs.scala-lang.org/overviews/compiler-options/index.html#:~:text=%2Drelease%20RELEASE%20or%20%2D%2Drelease%20RELEASE:

> `-release RELEASE` or `--release RELEASE`
> Compile for a specific version of the Java platform. Supported targets: 6, 7, 8, 9

So what are the supported targets? Only 6, 7, 8 and 9? Or also others?

**Comment by dalbani** [comment]
Just discovered https://github.com/scala/scala/pull/9982, having a look.

**Comment by som-snytt** [comment]
The confusion duplicates https://github.com/scala/docs.scala-lang/issues/1711

Worth adding, `scalac -help` is authoritative.
