### ISSUE TITLE
Empty table of contents on the glossary page

### ISSUE THREAD

**Issue by lorenzpahl** [scala/docs.scala-lang#2607]
The sidebar with the table of contents (TOC) on the [glossary page](https://docs.scala-lang.org/glossary/index.html) is currently empty. This is due to a change made by commit b88401fc (PR #1861). There, `h4` elements were excluded from the TOC. I think the easiest way to fix this would be to render the glossary terms using the `h3` element instead of `h4`.

**Comment by bishabosha** [comment]
Thanks for opening! I agree because I guess other pages will start adding too many levels of toc

**Comment by bishabosha** [comment]
looks like the search box functionality also depends on titles being h4
