### ISSUE TITLE
Deleted pages are not removed from the website

### ISSUE THREAD

**Issue by julienrf** [scala/docs.scala-lang#2621]
For some reason the deleted page https://docs.scala-lang.org/overviews/core/actors-migration-guide.html is still here. It seems that the script that pulls the new website content does not remove deleted pages.

_Originally posted by @julienrf in https://github.com/scala/docs.scala-lang/issues/2542#issuecomment-1301254543_

**Comment by julienrf** [comment]
@fsalvi could you please have a look?

**Comment by fsalvi** [comment]
By default, the script doesn't delete files but only update them to avoid the worst case where a random problem could lead to an empty site (but that can be changed in 2 seconds if needed).
Usually, the standard policy is more to replace deleted pages with redirects (using redirect_to) to avoid external links to the scala website returning a 404 error.

**Comment by julienrf** [comment]
Thank you Fabien, I see that the removed pages are effectively not available anymore on the server. However, that revealed that we had some dead links, as shown by the CI failure: https://github.com/scala/docs.scala-lang/actions/runs/3386648392/jobs/5626321883

**Comment by julienrf** [comment]
I am fixing the links in #2624
