### ISSUE TITLE
Tutorial for Ruby programmers

### ISSUE THREAD

**Issue by misfo** [scala/docs.scala-lang#275]
Is there one in progress right now? I'm new to Scala but have written enough Ruby that I have "legacy Ruby code" out there making people cry right now. I'd like to offer my help if someone's already writing one...

**Comment by SethTisue** [comment]
enough years have passed now that I think this is unlikely ever to happen. even if we had separate tutorials for people coming from different languages, they'd likely fall out of date. I think it's better to focus on 1) the language tour, 2) providing links to good external resources for teaching the language

we have "Scala for Java programmers" but that's special, the languages are so closely tied that it makes sense to make an exception there, IMO
