### ISSUE TITLE
Update the Scala for Python devs page

### ISSUE THREAD

**Issue by OlegAlexander** [scala/docs.scala-lang#2892]
Hello! I'm an experienced Python dev who's new to Scala. I was reading the Scala 3 book and noticed a few inaccuracies/omissions on the [Scala for Python devs page](https://docs.scala-lang.org/scala3/book/scala-for-python-devs.html). 

For example:

- Python has [type hints](https://peps.python.org/pep-0484/) that are checked by the [mypy type checker](https://mypy.readthedocs.io/en/latest/). 
- Scala case classes == Python dataclasses.
- Python supports metaprogramming in the forms of codegen+`eval`, monkey-patching, and ast transformations.

Would anyone mind if I submitted a PR to address some of these?

**Comment by bishabosha** [comment]
I'd support the first two, the third seems like it would be quite verbose

**Comment by OlegAlexander** [comment]
Thanks for your reply, @bishabosha! 

For the third point about metaprogramming, I was actually thinking of _removing_ text rather than adding it. The issue I was having when reading that page was mainly the section called "Concepts that are unique to Scala". There are 3 bullet points I'd remove from that list because these things are, in fact, available in modern Python:

- Case classes (Dataclasses added in Python 3.7)
- Pattern matching and match expressions (added in Python 3.10)
- Metaprogramming (has always been well supported because of dynamic typing)

So my plan is to delete those 3 points, add a little bit of info about Python type hints, and fix any other issues I find with a very light touch. I have no plans to make drastic changes to that page because it's already very good. 

Does that sound good to you?

**Comment by bishabosha** [comment]
Hey, thank you for layout out your plan, I'd say go ahead with the PR!

**Comment by OlegAlexander** [comment]
I submitted my PR. Please let me know if you'd like me to make any changes. Thank you.
