### ISSUE TITLE
Missing reference for "other advanced types" ?

### ISSUE THREAD

**Issue by vreuter** [scala/docs.scala-lang#2933]
The "other types" [page](https://docs.scala-lang.org/scala3/book/types-others.html) of the Scala 3 book lists a variety of "other advanced types" and links to the [reference documentation](https://docs.scala-lang.org/scala3/reference/index.html) "for more details on these types." For most of the listed sorts of types, there is reference easily accessible on the linked page, but for 2 of them there's nothing apparent (at least not when Ctrl+F searching on the page for these sorts of types):
- [ ] Singleton types
- [ ] Refinement types

It seems that either reference should be added for these on the linked page, or that more specific link(s) should be provided on the Scala 3 book page. Did I miss something, though?

**Comment by vreuter** [comment]
<img width="1362" alt="Capture d’écran 2023-12-13 à 12 09 28" src="https://github.com/scala/docs.scala-lang/assets/12036370/a2208486-2d97-49e7-82d4-a179d56dcb87">

**Comment by bishabosha** [comment]
Thanks for the feedback! that is indeed a missing information that is only visible in the [spec](https://scala-lang.org/files/archive/spec/3.4/03-types.html)

**Comment by vreuter** [comment]
> Thanks for the feedback! that is indeed a missing information that is only visible in the [spec](https://scala-lang.org/files/archive/spec/3.4/03-types.html)

Many thanks for the link @bishabosha

**Comment by gkepka** [comment]
Completed by #2934
