### ISSUE TITLE
Match expression's `@` operator not mentioned in docs

### ISSUE THREAD

**Issue by sdasda7777** [scala/docs.scala-lang#2999]
I would understand it not being included in [the docs](https://docs.scala-lang.org/scala3/book/control-structures.html#match-expressions ) if this was experimental feature, but it seems to work in both Scala 2 and Scala 3. Specifically I mean this extremely helpful `@` operator which allows you to both unapply the object for matching and upcast it for use in the code branch:
```scala
case a @ A(x) => a.classASpecificStuff()
case b @ B(x) if x > 0 => b.classBSpecificStuff()
```

**Comment by SethTisue** [comment]
It's not experimental, and I agree it's a strange omission.

I think https://docs.scala-lang.org/tour/pattern-matching.htm should cover it too.
