### ISSUE TITLE
No get started innformation

### ISSUE THREAD

**Issue by arctrong** [scala/docs.scala-lang#3055]
In Java I can create a `Hello.java`, compile it with `javac Hello.java`, and execute it with `java Hello`. On the Scala "Getting Stated" page <https://docs.scala-lang.org/getting-started/index.html> such scenario for Scala is not described. I didn't know Scala before and want to start learning it with this simple command line run. But what I see? SBT?! IDE?! These are not the steps I expected to see at my very start!

I think the information from <https://docs.scala-lang.org/scala3/book/taste-hello-world.html> may be added to the "Getting Started" page.

**Comment by bishabosha** [comment]
With 3.5.0 coming sbt won't be needed on the getting started page

**Comment by gkepka** [comment]
Completed by #3072
