### ISSUE TITLE
Use `scala-cli` for hello world example in getting started

### ISSUE THREAD

**Issue by scarf005** [scala/docs.scala-lang#3074]
https://docs.scala-lang.org/getting-started/index.html#create-a-hello-world-project-with-sbt

sbt is more involved than `scala-cli`. it might be a better idea to use scala-cli for basic introduction. I'm willing to open a PR.

**Comment by sjrd** [comment]
We already have a PR in progress: #3072.

**Comment by scarf005** [comment]
oh, sorry, haven't searched thru PRs.
