### ISSUE TITLE
Tour of Scala on mobile table of contents jumps off screen when scrolled down

### ISSUE THREAD

**Issue by benshine** [scala/docs.scala-lang#391]
When reading the Tour of Scala on an iPhone 5, and I zoom in to the content so that the actual text fills the screen, the table of contents starts out in the right position, but when I scroll down, the table of contents jumps far to the right, almost off screen. It then _stays_ offscreen even if I try to scroll to the right to see it. Combined with https://github.com/scala/scala.github.com/issues/390 it is really hard to read the Tour on an iPhone. 

Initial position:
![2014-11-29 08 29 01](https://cloud.githubusercontent.com/assets/21349/5235095/0085d7fc-77a2-11e4-84a9-55158b02fe17.png)

After scrolling down
![2014-11-29 08 29 04](https://cloud.githubusercontent.com/assets/21349/5235097/024b9482-77a2-11e4-9c3f-5afe3a3224a2.png)

**Comment by kzys** [comment]
Will SCP-008 address the issue?
https://github.com/scalacenter/advisoryboard/blob/master/minutes/003-2016-q4.md#proposal-scp-008-maintain-scala-lang-docsscala-lang-scalaepflch-websites

**Comment by SethTisue** [comment]
> Will SCP-008 address the issue?

My understanding is that 47 Degrees is working on some CSS changes that are improving responsiveness, so yes, I think it would make sense to sit tight on this for now and wait for their changes to land.

**Comment by SethTisue** [comment]
someone want to see if #606 fixes this?

**Comment by SethTisue** [comment]
can anyone check on this...? I suggest we simply close the ticket unless someone can verify that the problem still exists.

**Comment by gkepka** [comment]
No longer relevant: the table of contents is at the bottom of a page now.
