### ISSUE TITLE
Tutorial for PHP developers

### ISSUE THREAD

**Issue by greydnls** [scala/docs.scala-lang#411]
Similar to #275 

I'm new to scala, but very well versed in PHP. I'd be happy to help with any tutorial geared towards PHP devs.

**Comment by heathermiller** [comment]
Hi Kayla! ...A PHP-to-Scala guide would be awesome. I'd be happy to help you structure it and when it comes time, proofread and edit it :)

**Comment by seralf** [comment]
Hi I'll be glad to give some help/contribution if needed! :-)

**Comment by cdshines** [comment]
asfaf

**Comment by maltiyadav** [comment]
I would be glad to help moving from PHP to Scala.

**Comment by heathermiller** [comment]
Hi @maltiyadav – we're happy for help. It just takes getting started... The above still stands – if you're interested in helping to write a PHP-to-Scala guide, I'd be happy to help you figure out how to structure it and when it comes time, proofread/edit. 

Just let me know how you'd like to proceed :)

**Comment by maltiyadav** [comment]
Hi @heathermiller  Thank you for writing me. It would be my pleasure to writing  a PHP-To-Scala guide. Please let me know how we can proceed :)
I think , we can start with a piece of code.

**Comment by heathermiller** [comment]
Would you like to start by structuring it in a Google doc perhaps? I've created one here: https://docs.google.com/document/d/1lQs8OFGdGIhMKjpy4IdSaZvJtAOjQs87VAWlkwQdUno/edit?usp=sharing

Could you email me with a Google account that I can use to give you edit rights to the document? From there, maybe we can sketch out a structure together :)

**Comment by seralf** [comment]
can I contribute with some comment, in case? :-)

2016-03-22 18:37 GMT+01:00 Heather Miller <notifications@github.com>:

**Comment by maltiyadav** [comment]
Thank @heathermiller . My gmail a/c is - maltiyadava@gmail.com

Please share the google docs.

**Comment by heathermiller** [comment]
Hi @seralf! You're very welcome to help as well. Actually it might be good to have two people who are more familiar with PHP work together, as I've never been in the position to go from PHP to Scala. WDYT? 

The first step would be likely to make an outline of possible sections of the guide in the doc I linked to above.

@seralf if you email me your Google account, I can also add you to the doc :)

**Comment by seralf** [comment]
Hi thank you

my email is simply my username [AT] gmail ;-)

2016-03-23 13:57 GMT+01:00 Heather Miller <notifications@github.com>:

**Comment by heathermiller** [comment]
@seralf you've been added! :)

So, first step: outline of possible sections of the guide?

**Comment by SethTisue** [comment]
see my remarks at https://github.com/scala/docs.scala-lang/issues/275#issuecomment-406100177
