### ISSUE TITLE
Daniel Sobral's FAQ Corner, front page

### ISSUE THREAD

**Issue by heathermiller** [scala/docs.scala-lang#42]
Need to make a place for Daniel to add his FAQs to. 

The geoal is to have them have their own subsection on the doc-site (assuming FAQ pages keep being added). But it'd also be nice to give them a place on the front page- for example, two or three could randomly be chosen and displayed.

**Comment by SethTisue** [comment]
https://docs.scala-lang.org/tutorials/FAQ/index.html exists and is prominently linked from the front page

(but the content is very stale...)
