### ISSUE TITLE
External Guides Section

### ISSUE THREAD

**Issue by heathermiller** [scala/docs.scala-lang#50]
Would be nice if there was some place to aggregate quality external guides out there, like Twitter's Scala School, or Twitter's Effective Scala, amongst others. 

This should be its own section, or be a subsection on individual pages if #36 would be implemented.

**Comment by SethTisue** [comment]
fwiw, http://www.scala-lang.org/community/ has a "Community-Powered Learning Resources" section

**Comment by SethTisue** [comment]
...which seems like an adequate solution to me
