### ISSUE TITLE
Artefacts in classhierarchy.img_assist_custom.png make it hard to read

### ISSUE THREAD

**Issue by kventil** [scala/docs.scala-lang#511]
Hi
the overview of the class hierachy is very hard to read due to compression artefacts.
([http://docs.scala-lang.org/resources/images/classhierarchy.img_assist_custom.png](http://docs.scala-lang.org/resources/images/classhierarchy.img_assist_custom.png))

Is it possible to generate a bigger version?

**Comment by jarrodwb** [comment]
It looks like this is not being compressed by the the build. It was added to the repo as a compressed file way back in 2011.

https://github.com/scala/scala.github.com/commits/master/resources/images/classhierarchy.img_assist_custom.png

I do agree that it is hard to read.

**Comment by SethTisue** [comment]
see also discussion at https://github.com/scala/scala.github.com/issues/615

**Comment by Philippus** [comment]
@SethTisue let's close this one?
