### ISSUE TITLE
ScalaObject no longer exists, but appears in diagram

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#615]
namely the diagram at http://docs.scala-lang.org/tutorials/tour/unified-types.html

**Comment by soc** [comment]
http://get-scala.org/documentation/overview/unified-types.

**Comment by jarrodwb** [comment]
Where is the source that creates these figures? Are they LaTeX or something else? It seems like they should be in version control. That is if they are not already.

I looked for them at some point in the past. I was thinking at the time that the resolution should be improved. They seem a bit grainy and hard to read on my display.

**Comment by soc** [comment]
@jarrodwb I spent some time searching for them through old documentation. I was fairly sure at that time that the source existed somewhere, but that was a long time ago. I think I started redoing the diagram in SVG a while ago, but got more important priorities shortly after that.

**Comment by jarrodwb** [comment]
Do you still have the SVG file around somewhere? It can be version controlled in a human readable way.

**Comment by SethTisue** [comment]
@heathermiller do you remember anything about this perchance?

**Comment by lrytz** [comment]
The same image is in the spec - interestingly the image is broken on the html version (http://scala-lang.org/files/archive/spec/2.11/12-the-scala-standard-library.html), but it's here as a pdf: https://github.com/scala/scala/blob/2.12.x/spec/public/images/classhierarchy.pdf. I don't know about the source..

**Comment by Philippus** [comment]
I made a high resolution version from the pdf and removed ScalaObject. Maybe this will suffice until someone creates a new diagram?

![classhierarchy_without-scala-object-from-pdf](https://cloud.githubusercontent.com/assets/1923596/23277662/00ff615c-fa0f-11e6-8b0b-741b8f89bd4b.png)

**Comment by SethTisue** [comment]
@Philippus that's a huge improvement! note that over at https://github.com/scala/scala.github.com/pull/708 @travis032654 is working on overhauling this page, so maybe Travis could include this in his efforts, or maybe he's already made his own new version.

**Comment by travis032654** [comment]
@Philippus thanks for making this diagram. @SethTisue I did make a [simplified version](https://github.com/travis032654/scala.github.com/blob/d5975e4ef9e2e4a83e706d969ff9c1aa619feaae/tutorials/tour/unified-types-diagram.svg)

**Comment by Philippus** [comment]
I've made a PR for the spec: https://github.com/scala/scala/pull/6647
