### ISSUE TITLE
Todos section of individual document pages

### ISSUE THREAD

**Issue by heathermiller** [scala/docs.scala-lang#64]
Some pages in the collections overview, for example have become outdated. It's up-to-date with respect to Scala 2.8, but not Scala 2.9-- in particular, there's no mention of the `Gen` traits that had to be introduced due to the introduction of parallel collections in 2.9.

Collections isn't the only place where this is the case. This is also an issue on other documents as well.

For reasons like these, it'd be nice to have a "ToDos" or "this doc needs some revisions" note on the page, with a list of what needs to be done-- so committers/community can make revisions as they find them.

**Comment by SethTisue** [comment]
let's just track it here in this issue tracker, that's de facto what we've been doing all these years
