### ISSUE TITLE
Style guideline should tell how to deal with acronym

### ISSUE THREAD

**Issue by Atry** [scala/docs.scala-lang#665]
In http://docs.scala-lang.org/style/naming-conventions.html#classestraits, it said that:
> Classes should be named in upper camel case:

However, there is not a rule about how to deal with acronym.

In Scala Standard Library and other Lightbend libraries, some acronyms are named in all upper cases, and others are named in upper camel case.
For example:
 * upper camel cases:
   * `scala.xml.Xhtml`
   * `play.api.libs.json.Json`
   * `scala.Enumeration.maxId`
 * all upper cases:
   * `scala.xml.XML` 
   * `scala.util.parsing.json.JSON`
   * `scala.swing.Applet.UI`
   * `scala.sys.process.ProcessIO`
   * `scala.SerialVersionUID`

**Comment by Atry** [comment]
I myself found that it's hard to turn some terms into camel cases, like `JavaFX`, `OpenGL`, `macOS`. It would be great if there is a guideline.

**Comment by sjrd** [comment]
FWIW, in Scala.js we consistently use all-uppercase for acronyms, unless they are the first word of the camelCase identifier, in which case they are all lowercase. Examples:

* `scalaJS`
* `js`
* `parseJSON`

**Comment by SethTisue** [comment]
I like Sebastien's rule. I would add that package names should always be all lower case.

**Comment by chen3feng** [comment]
Treat acronym words as normal words make everything easy. reasons:
- In variable and package names, acronym are already be all lower case, there is nothing special in type names
- Keep acronym all uppercase is embarrassed when two acronym words appear together, such as XMLHTTP.
- More readable
- Easy to be implemented by computer, such as convert protobuf message field name to Java method name
See https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

**Comment by dwijnand** [comment]
> I found that it's hard to turn some terms into camel cases, like `JavaFX`, `OpenGL`, `macOS`.

👨‍🎨 `JavaFx`, `OpenGl`, and `MacOs` look reasonable to me.

I'm with @chen3feng and the Google style guide, particularly because of the nearly deterministic scheme it uses and because it solves the `XMLHTTPRequest` problem.

(Obviously a 🚲🏚-ing issue, so ☮️)
