### ISSUE TITLE
"overview-large" docs have less-than-appealing titles

### ISSUE THREAD

**Issue by heathermiller** [scala/docs.scala-lang#68]
This is both in the sense of the title of the actual window as well as the title of the page. Nowhere on the page does it say the title of the actual collection of documents. 

Original suggestion:

> Speaking of which, do you plan on writing an index.md for the guide?
> If ppl bookmark the write up it'd say "Overview - Scala Documentation"
> and nowhere on the page it says Scala Parallel Collections Guide. If
> not maybe include the overview name as part of the title, maybe?

**Comment by SethTisue** [comment]
I don't really get this. maybe it got addressed in the redesign, or before, even? provisionally closing, we can reopen if someone understands more clearly what this is.
