### ISSUE TITLE
SIP MD to HTML translation issues

### ISSUE THREAD

**Issue by soronpo** [scala/docs.scala-lang#689]
I don't know if this is fixable, but currently there is unwanted result where a SIP `MD` file is translated to `HTML` and looks different. I noticed the following issues:
1. Acceptance of the ` ``` {code} ``` ` code annotation, and more specifically a ` ```scala {code} ``` ` annotation. Currently the only way to achieve the wanted result for the site is to use a `{% highlight scala %} {code} {% endhighlight %}` annotation. If we don't add ` ``` `, then it will look horrible on GitHub or any MD editor, but this adds extra viewable unwanted ` ``` ` to the site. The alternative is to use a 4-space prefix to the code. Unfortunately, this make all code on the site to have extra 4 space characters.
2. MD accepts `##Subject`, but the the site translation expects space `## Subject`.
3. MD accepts 
```
---
# Subject
```
The site expects an empty line
```
---

# Subject
```

**Comment by SethTisue** [comment]
is this still applicable on the current site?

**Comment by Philippus** [comment]
Let's check with https://github.com/scala/docs.scala-lang/pull/1487 and update the https://github.com/scala/docs.scala-lang/blob/master/_sips/sip-template.md accordingly.

**Comment by NthPortal** [comment]
The [by-name implicits SIP](https://github.com/scala/docs.scala-lang/blob/be16a0a472f335eefdf36997f6ceb4da37efe9ea/_sips/sips/2017-11-20-byname-implicits.md) uses regular GFM markdown blocks, and renders fine on the site ([link](https://docs.scala-lang.org/sips/byname-implicits.html)).
