### ISSUE TITLE
add Discourse without generating huge email flood?

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#795]
@travissarles is it possible for this to happen without my inbox looking like this? I must have gotten more than a hundred of these in recent days.

if it's only my inbox, it's nbd. does every user's inbox look like this? if so, I'm afraid we'll lose subscribers.

<img width="1303" alt="screen shot 2017-06-12 at 8 39 46 am" src="https://user-images.githubusercontent.com/161079/27021773-e5094508-4f4a-11e7-903e-eb56890c0d2e.png">

**Comment by heathermiller** [comment]
For reference, I posted this on the Discourse help forum:
https://meta.discourse.org/t/flood-of-emails-from-embedded-discourse/64341

**Comment by SethTisue** [comment]
Jeff's reply is 😱 — perhaps the plan to use Discourse for page comments will have to be abandoned entirely

**Comment by SethTisue** [comment]
Idea off the top of my head: how hard would it be to set up a third, separate Discourse instance and use it only for this? What would the downsides be?

**Comment by heathermiller** [comment]
Jeff's reply is sort of off-topic. I still think that the behavior of Discourse in embedded mode is a bit nuts. It would make sense that Discourse creates a new thread when someone clicks "start discussion". But not when they visit a page that embeds Discourse comments...

**Comment by heathermiller** [comment]
I re-asked the question in the Discourse thread. 🤞 for an answer to the embedded mode behavior.

**Comment by martijnhoekstra** [comment]
As a workaround, can we just visit all doc pages while we're not in email mode for the topic so that everything gets created and we can start from there when the flood has subsided?

**Comment by nafg** [comment]
I did suggest not deprecating google groups until discourse proved itself...

I am really not happy with discourse. Mailing list mode is still terrible for a number of reasons. I used to be able to contribute to questions and discussions a lot more, because I could just hit reply in my inbox. With discourse, threads are hard to read, my replies get sent back to me, and other people's replies come very late. I have too many browser tabs open already, I'm just not opening new tabs for topics unless I have a pretty strong reason to chime in. And the mobile app is terrible.

**Comment by nafg** [comment]
Also some of the replies in the meta discourse seem like red flags.

> I'd not take @codinghorror's warning lightly - discourse is being developed for the future, and the discourse core team see mailing lists as the past.

Worn-out platitude...

> So at best mailing list mode is a compromise and you will always bump up against difficulties if you try to make it the default way people participate in your community. There are alot of topics about this here on meta you may want to read up on.

And if I as an individual turn mailing list mode on will I bump up against difficulties?

These seem like excuses. There's no good reason they can't improve mailing list mode.

> > Would it be possible to only create the topic when someone publishes a comment?

> No, it is a huge change architecture wise. On Discourse you need to post replies on topics. There is no concept of "replying to a topic that doesn't exist yet."

Is their code so terrible that adding a new capability is a huge architecture change?

**Comment by SethTisue** [comment]
@nafg the place to register your general feedback on Discourse is... on Discourse, and not here on this ticket, which we'd like to keep focused on the specific technical problem we're trying to solve.

**Comment by heathermiller** [comment]
Seems like this is resolved now.

I removed Discourse from non-English pages, and Discourse topics have been created for each documentation page. So the flood of new topics appears to have been quelled.

**Comment by SethTisue** [comment]
I got a flood of 95 more emails this morning.

**Comment by SethTisue** [comment]
I shouldn't have used the past tense — the flood is continuing. I just got another one.

I noticed this one said "WARNING: you reached the limit of 100 daily emails. Further email notifications will be suppressed."

**Comment by heathermiller** [comment]
I know what happened! The PR that added permalinks to some pages caused this (to fix missing .html suffixes). It seems Discourse creates new entries in its database for new pages based on the URL. 

That said, I imagine this will become problematic again once the overhaul PR is merged.

We should figure out how to mute the Documentation topic until a few weeks after the overhaul is merged.

**Comment by SethTisue** [comment]
I still occasionally get one of these emails, but oh well.
