### ISSUE TITLE
Justify scala cheatsheets

### ISSUE THREAD

**Issue by Abrasha** [scala/docs.scala-lang#808]
Link: [scala cheatsheets](http://docs.scala-lang.org/cheatsheets/).

It is quite hard to read this cheat shit due to its formatting.

![Scala cheatsheets](https://user-images.githubusercontent.com/11317222/28247345-000c0fb4-6a37-11e7-8675-0fd48bba33a6.png)

The reason of having this is aside menu on the top:

![Scala cheatsheets aside menu](https://user-images.githubusercontent.com/11317222/28247355-33d6e7ba-6a37-11e7-8dac-e60466c2169f.png)

Can we make this page justified? Something like this:

![Scala cheatsheet proposal](https://user-images.githubusercontent.com/11317222/28247367-6e9be7c4-6a37-11e7-955d-2f0fdbe7099b.png)

I believe this can be achieved by making menu horizontal and be placed on top.

**Comment by SethTisue** [comment]
unless I misunderstand, this seems to have been fixed at some point
