### ISSUE TITLE
Add build info + Jenkins badge to README

### ISSUE THREAD

**Issue by heathermiller** [scala/docs.scala-lang#813]
Build for this repo is now here: 
https://scala-webapps.epfl.ch/jenkins/job/build_docs_scala_website/

**Comment by SethTisue** [comment]
curious why this change was made?

(and does it make sense that we're still using the `github-pages` gem?)

**Comment by SethTisue** [comment]
ah, over at #803 I see:

> Heads up though; @fsalvi just moved this build to EPFL machines, which means we can now add plugins and use https (plugins are required for #806)
> The build is here: https://scala-webapps.epfl.ch/jenkins/job/build_docs_scala_website/

**Comment by heathermiller** [comment]
Yes, merging the look and feel of the new redesign of scala-lang required plugins which were impossible to use on GitHub Pages.

That, and https wasn't possible on GitHub pages with a custom domain.

**Comment by Philippus** [comment]
I assume we would need something like https://wiki.jenkins.io/display/JENKINS/Embeddable+Build+Status+Plugin installed on the Jenkins machine

**Comment by SethTisue** [comment]
the README has a "backend" section with a link to the Jenkins info. tbh, I'm tempted to just close this as not being worth the effort, really
