### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#814]
now that the docs site is no longer built by GitHub Pages, I suggest we rename the repo to "docs.scala-lang". the old name has always been misleading

**Comment by heathermiller** [comment]
We could do this, sure. I agree the name is awful (stems from early GH Pages naming conventions.)

Though, basic question; do you know if a repo rename would require everyone who has checked out scala.github.com now can no longer push up to it without adding a new remote? Or does GitHub have some kind of way of managing redirects?

**Comment by SethTisue** [comment]
they redirect it. https://help.github.com/articles/renaming-a-repository/ says so, and my firsthand experience with this in other repos has been smooth

**Comment by heathermiller** [comment]
Suggested name?

**Comment by heathermiller** [comment]
scala/docs.scala-lang.org?
scala/documentation?

**Comment by SethTisue** [comment]
scala-lang.org repo name is scala/scala-lang, so I would suggest scala/docs.scala-lang . (but I wouldn't object if you like it better with the .org at the end)

**Comment by heathermiller** [comment]
Sure, docs/scala-lang sounds good. 

I'll wait on this though until the overhaul is merged. I know it probably won't interfere with the massive merge, but just as a precaution...

**Comment by SethTisue** [comment]
as a bonus, renaming the repo will fix #815. (this came up again at #852)

**Comment by SethTisue** [comment]
@heathermiller ok to go ahead with this?

**Comment by ashawley** [comment]
Maybe just **scala/docs** or **scala/scala-lang-docs**?  But **scala/documentation** is also good.  **docs.scala-lang.org** probably makes the most sense for clarity.

I second Seth, I've also had a good experience after renaming repos on GitHub.

**Comment by heathermiller** [comment]
Done :) 
Let me know if anybody has any issues at any point with this!
