### ISSUE TITLE
inconsistent html suffix

### ISSUE THREAD

**Issue by buhman** [scala/docs.scala-lang#836]
The top google result for `scala symbols` is http://docs.scala-lang.org/tutorials/FAQ/finding-symbols which is 404. It looks like the correct url might be http://docs.scala-lang.org/tutorials/FAQ/finding-symbols.html. 

There are several other previously-indexed pages as well: https://www.google.com/search?q=-filetype:html+site:docs.scala-lang.org (starting on page 2).

Another thing I noticed is that if you somehow get a link like this: http://docs.scala-lang.org/tutorials/tour/singleton-objects.html.html the links on the sidebar also contain `.html.html`, but not all pages' navigation have this behavior.

Because both suffixed and non-suffixed pages are currently indexed, I think it probably makes sense, for discoverability, to support both but perform some sort of redirect and navigation normalization to whichever is desired.

**Comment by Philippus** [comment]
The top google result for `scala symbols` has changed by now (for me at least). And I think most of this has been fixed after https://github.com/scala/docs.scala-lang/issues/1606#issuecomment-568444771.

**Comment by SethTisue** [comment]
@Philippus um, I haven't really followed this saga, but if nobody's been complaining recently, I'd be okay with closing the ticket, we can always reopen it if new complaints come in
