### ISSUE TITLE
Editing issue in Tour of Scala

### ISSUE THREAD

**Issue by Excessionist** [scala/docs.scala-lang#845]
In section "Unified Types", 3rd paragraph of "Scala Type Hierarchy", the third sentence (in bold below) stops abruptly (after "AnyRef"). It is not self-evident what the rest of the sentence is supposed to be:

"AnyRef represents reference types. All non-value types are defined as reference types. **Anywhere an AnyRef** Every user-defined type in Scala is a subtype of AnyRef. If Scala is used in the context of a Java runtime environment, AnyRef corresponds to java.lang.Object."

**Comment by Philippus** [comment]
fixed in https://github.com/scala/docs.scala-lang/pull/861
