### ISSUE TITLE
The Tour of Scala «Page not found»

### ISSUE THREAD

**Issue by blastoms** [scala/docs.scala-lang#852]
http://scala.github.io/getting-started.html page has incorrect link on «The Tour of Scala» page in the « Next Steps» (http://scala.github.io/tutorials/tour/tour-of-scala.html)

**Comment by heathermiller** [comment]
You should be visiting docs.scala-lang.org, not scala.github.io (we're in the process of getting rid of scala.github.io) 

cc/ @SethTisue

**Comment by ashawley** [comment]
Looks like this is in progress at #815

**Comment by SethTisue** [comment]
renaming the repo (#814) will fix it

**Comment by blastoms** [comment]
Got it
