### ISSUE TITLE
tour/lower-type-bounds : First code block is not styled properly

### ISSUE THREAD

**Issue by lierdakil** [scala/docs.scala-lang#864]
I assume generator doesn't define `tut:fail` environment, but it's used nonetheless. Not creating a PR since it was fixed before in 1f4e98b746ee3e113e6ba61914d1911ff3debd23, but swiftly reverted for some reason in 0cdfd54673ee6d1d524c530102486b0c1ae8cd15.

A screenshot showing the problem:
![image](https://user-images.githubusercontent.com/7275622/29308364-50c2cb80-81ae-11e7-98ae-c97b6446d386.png)

**Comment by heathermiller** [comment]
Ah weird, my fix for that worked locally! Wonder what happened; must be the wonky Jekyll plugin we have. I'll look into it. Thanks for catching this!
