### ISSUE TITLE
mixin - statement is confusing

### ISSUE THREAD

**Issue by vsacheti** [scala/docs.scala-lang#869]
`def foreach(f: T => Unit): Unit = while (hasNext) f(next())`

This should be explained more clearly. Currently this syntax is  very confusing to a new learner of scala.

This is part of this page - http://docs.scala-lang.org/tour/mixin-class-composition.html

**Comment by SethTisue** [comment]
a pull request adding a link here, linking to a relevant other section of the tour, would be welcome

**Comment by SethTisue** [comment]
@vsacheti what do you think of #1027, does that address it in your opinion?

**Comment by vsacheti** [comment]
👍
