### ISSUE TITLE
broken link in "getting started", sbt track

### ISSUE THREAD

**Issue by JosefAssad** [scala/docs.scala-lang#870]
On [this page](http://www.scala-lang.org/documentation/getting-started-sbt-track/getting-started-with-scala-and-sbt-in-the-command-line.html), the up next link to testing Scala with sbt way at the bottom of the page 404s.

**Comment by heathermiller** [comment]
This is an issue with the scala-lang repository.

**Comment by heathermiller** [comment]
This should fix it: https://github.com/scala/scala-lang/commit/260ed434d4b156a87de0baf058368968fa94ddc0

**Comment by heathermiller** [comment]
Thank you for reporting! It's appreciated 🙂
