### ISSUE TITLE
Outdated SIP links

### ISSUE THREAD

**Issue by soronpo** [scala/docs.scala-lang#872]
http://docs.scala-lang.org/sips/ is the new link vs. http://docs.scala-lang.org/sips/pending/
I was looking at my own SIP and at first I couldn't understand why I remember updating something, yet it remained the same.

**Comment by heathermiller** [comment]
Seems we neet to put redirects in place from `sips/pending` to `sips/`. I thought I did that but it seems I didn't.

**Comment by smarter** [comment]
+1. Googling "sip 23" for example will bring you to the old, outdated pending/42.type.html. The correct one does not appear anywhere in Google search results.

**Comment by adriaanm** [comment]
Ping. I tried to figure out how to do this with a PR, but I don't even see the pending directory there. Could someone look into removing this confusion? Maybe it's just a stray folder on the webserver?

**Comment by heathermiller** [comment]
It seems there are pages in an old directory on chara. It's not all bad though. For example, if these pages were all deleted, [this article about the statistics behinds the MOOCs](http://docs.scala-lang.org/news/functional-programming-principles-in-scala-impressions-and-statistics.html) would be lost. 

Perhaps the best thing to do is:
1) find this old directory
2) put in place redirects where problematic?

Reason I suggest this is that I don't know how many potentially useful pages we haven't migrated to the new site. Perhaps there are many pages that don't have an analog on the new doc site. Simply deleting the old directory would delete these pages for good.

**Comment by smarter** [comment]
> It seems there are pages in an old directory on chara. It's not all bad though. For example, if these pages were all deleted, this article about the statistics behind the MOOCs would be lost.

I don't see that page on http://docs.scala-lang.org/sips/pending/, could we delete just that subdirectory?

**Comment by smarter** [comment]
> > It seems there are pages in an old directory on chara. It's not all bad though. For example, if these pages were all deleted, this article about the statistics behind the MOOCs would be lost.
>
>I don't see that page on http://docs.scala-lang.org/sips/pending/, could we delete just that subdirectory?

Ping two months later. I still think this makes sense, but I can't do it myself.

**Comment by adriaanm** [comment]
Moved that folder out of the way by editing the [jenkins job](https://scala-webapps.epfl.ch/jenkins/job/build_docs_scala_website/176/console). I don't have direct access. Nothing else was touched.

**Comment by adriaanm** [comment]
Also removed offending redirect_froms, and added one to sips/all.md. Should be good now

**Comment by SethTisue** [comment]
the issue on adding redirects so that old links aren't 404 is https://github.com/scala/docs.scala-lang/issues/1047
