### ISSUE TITLE
Read Next page on Tour of Scala

### ISSUE THREAD

**Issue by KipTwitchell** [scala/docs.scala-lang#875]
The comment at the bottom of the screen telling the user to select the next page would be more clear if there was a button close to it, or at least refer to the table of contents.  It wasn't clear the two were connected.

http://docs.scala-lang.org/tour/tour-of-scala.html

**Comment by adonig** [comment]
Yep, +1. Came here exactly to report the same issue. Would be nice to have a link like:

> Please continue to [the next page](http://docs.scala-lang.org/tour/basics.html) to read more.

**Comment by som-snytt** [comment]
A bad link on that first page:

>Furthermore, Scala’s notion of pattern matching naturally extends to the processing of XML data with the help of right-ignoring sequence patterns, by way of general extension via extractor objects.

"sequence patterns" is a link to using `Regex` in a pattern match, but I think it used to be about ancient regex syntax in match expressions; it looks like the tour doesn't mention `unapplySeq`, which is probably just as well.

I find that whole paragraph confusing. Maybe there's a feature that makes Scala an easy sell for web services?

But whoever adds a link at the bottom could at least remove the offending link described.

**Comment by rillig** [comment]
The "link to the next page" should be on _every_ page, not only the first. As an interested reader, I want to cover all topics, one after another. For this, scrolling to the top after each page is unnecessary and error-prone, especially since the current topic is not highlighted in the contents.

**Comment by SethTisue** [comment]
fixed by #961
