### ISSUE TITLE
A joint use of both features 

### ISSUE THREAD

**Issue by rchavez2** [scala/docs.scala-lang#876]
"A joint use of both features facilitates the definition of new statements without using meta-programming facilities such as macros."

Which two features? 

They are actually mentioned in other languages but are missing here in the English version.

**Comment by heathermiller** [comment]
It would be most helpful if you could tell us which document this quote comes from.

**Comment by rchavez2** [comment]
It's in Introduction (tour-of-scala.html) > Scala is extensible.

**Comment by SethTisue** [comment]
#896
