### ISSUE TITLE
Display error on "Getting Started" page

### ISSUE THREAD

**Issue by nguyenlamlll** [scala/docs.scala-lang#906]
The display error can be found on this page here: [Building a Scala project with IntelliJ and SBT](https://www.scala-lang.org/documentation/getting-started-intellij-track/building-a-scala-project-with-intellij-and-sbt.html)

Under the part "Running the project": Instead of showing numbers of age (like in markdown file), the HTML page shows `currentYear - 1` and `currentYear - 2`.

**Comment by Philippus** [comment]
Not sure if https://github.com/scala/scala-lang/pull/773 will get this page fixed, because it may be an older page. There's also: http://docs.scala-lang.org/getting-started-intellij-track/building-a-scala-project-with-intellij-and-sbt.html
