### ISSUE TITLE
Long sidebars don't scroll until you reach the bottom of the page

### ISSUE THREAD

**Issue by Matt343** [scala/docs.scala-lang#916]
If a page has a sidebar that is long enough to extend past the bottom of the screen (like https://docs.scala-lang.org/glossary/), you cannot see the bottom portion of the sidebar without scrolling to the bottom of the entire page. This makes using the sidebar for navigation clumsy, since you usually want to use the sidebar to avoid scrolling all the way down the page. This is particularly bad on lower resolution screens.

Here is what the sidebar looks like when halfway down the page: https://i.imgur.com/zk1auSv.png

Here is what it looks like at the bottom of the page: https://i.imgur.com/wEeQERD.png

Tested on Chrome on Windows and Ubuntu

**Comment by heathermiller** [comment]
PR welcome!
