### ISSUE TITLE
Wrong YouTube event appearing on SIP page

### ISSUE THREAD

**Issue by darjutak** [scala/docs.scala-lang#917]
I created an event for the next SPP meeting, but the sidebar of the SIP website says theres a SIP meeting coming up instead: http://docs.scala-lang.org/sips/all.html
![screen shot 2017-11-02 at 16 34 35](https://user-images.githubusercontent.com/31061184/32334836-ca536416-bfeb-11e7-81e3-4d5c92c0d013.png)

If you click the link, it goes to a YouTube Live event called "SPP Meeting," so the sidebar should read "November SPP meeting" rather than SIP meeting...

@heathermiller or anyone else interested, could you have a look?

**Comment by SethTisue** [comment]
@jvican?

**Comment by jvican** [comment]
No idea what's up here, but I doubt I'll find time soon to fix it. Putting on the backburner for now.
