### ISSUE TITLE
Pages with TOCs not navigable when window width <= 768px

### ISSUE THREAD

**Issue by aaron-kaplan** [scala/docs.scala-lang#925]
The table of contents is not visible on my phone, which makes it impossible to navigate the Scala Tour. I can reproduce this behavior on desktop by resizing the browser window to 768 pixels wide.

[description edited after clarification below]

**Comment by heathermiller** [comment]
Yes, this is by design. I wouldn't say that it's "impossible to navigate the site" though, is it? You just don't get a table of contents for the page you're viewing... You still have all other navigation (top navbar, footer, etc)

**Comment by aaron-kaplan** [comment]
I should have said that it makes it impossible to navigate the tour. The top nav and footer have links to other parts of the site, but I don't see links to other pages of the tour. The intro page has in-line links to many of the pages of the tour, but not all of them. Am I missing something?

**Comment by heathermiller** [comment]
Aha, yes ok, you're right. The Scala Tour is a multi-page document that actually needs the table of contents to navigate. I guess it's the only exception on the site. Good point–so we should figure out a way to show a TOC for at least this one document...

**Comment by marconilanna** [comment]
> The Scala Tour is a multi-page document that actually needs the table of contents to navigate. I guess it's the only exception on the site.

@heathermiller it also affects multiple overview documents:

* http://docs.scala-lang.org/overviews/reflection/overview.html
* http://docs.scala-lang.org/overviews/macros/usecases.html
* http://docs.scala-lang.org/overviews/quasiquotes/setup.html
* http://docs.scala-lang.org/overviews/collections/introduction.html
* http://docs.scala-lang.org/overviews/parallel-collections/overview.html
* http://docs.scala-lang.org/overviews/scaladoc/overview.html

**Comment by SethTisue** [comment]
the tour sections have "previous" and "next" links now, but that doesn't help the other pages.

**Comment by rkoeninger** [comment]
These lines are what cause the TOC to be hidden when the page width is less than 768px:

https://github.com/scala/docs.scala-lang/blob/44840f559bff75de755b04c457838d046c5edbd4/_sass/layout/toc.scss#L6-L8

Should this just be removed? If it were, the TOC would always be visible, even on small screens. TOC isn't that big, not sure why it would need to be hidden.

And forcing it to appear only for certain pages would be complicated. (Maybe there would be a flag in the article's markdown that causes a class to be added or removed from the TOC div and the css in the media query includes that class, or `:not()`?)

Or just always show the TOC.

**Comment by gkepka** [comment]
Completed by #2969
