### ISSUE TITLE
Font contrast issue for "Filter All Members"

### ISSUE THREAD

**Issue by wenyangfu** [scala/docs.scala-lang#937]
While browsing API docs for [Scala 2.12.4](http://www.scala-lang.org/files/archive/api/2.12.4/scala/), I noticed that the font contrast for "filter all members" could use some adjustment; it was very difficult to read the words due to faint contrast. Personally, I think other users would be confused by the purpose of this box (as I was initially).

I've highlighted the element in question with a blue box:
![scaladocs-filter-font-contrast](https://user-images.githubusercontent.com/6570181/33387964-3e4bd444-d4f4-11e7-9a69-71813f1a22c7.png)

I believe this affects all docs for Scala 2.12.x.

**Comment by SethTisue** [comment]
could you open this over at https://github.com/scala/bug/issues instead? although the files are hosted on scala-lang.org, they're generated by the Scaladoc tool, so the fix would have to be made in the scala/scala repo (and we keep scala/scala issues in scala/bug)

**Comment by SethTisue** [comment]
very good catch, by the way!

**Comment by wenyangfu** [comment]
Got it, will do! :)
