### ISSUE TITLE
Inconsistent style of doc sites in different language

### ISSUE THREAD

**Issue by TisonKun** [scala/docs.scala-lang#938]
Now our style of https://docs.scala-lang.org/zh-cn/overviews/ is different from that of https://docs.scala-lang.org/overviews/ and of https://docs.scala-lang.org/ja/overviews/ , which two are in the same.

I wonder the reason why it arrives here, and whether we're supposed to unify the style?

@heathermiller (wish i don't \at a wrong member)

**Comment by SethTisue** [comment]
surely just an oversight of some kind, but I don't know what the cause is.

**Comment by exoego** [comment]
You can now translate the page into your language with a redesigned theme.
Refer the instruction in https://github.com/scala/docs.scala-lang/pull/1467#issue-302398159

**Comment by TisonKun** [comment]
Thanks @exoego !
