### ISSUE TITLE
Scala standard library: SIP or SPP?

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#943]
http://docs.scala-lang.org/sips/index.html has the Scala standard library as under the control of the SPP committee. Is that really the case? My understanding was that since SLIP was shut down, the core Scala standard library went back under SIP, and that SPP covers everything *but* scala-library.jar.

(@jvican? @adriaanm?)

**Comment by jvican** [comment]
@SethTisue IIRC, the consensus is that the SIP Committee is in charge of the to-be Scala Core, whereas anything considered previously part of the Scala Library will be under control of the SPP Committee. Does this sound reasonable?

**Comment by adriaanm** [comment]
I’d say the standard library is part of the core, once we’re done
modularising in 2.13

**Comment by SethTisue** [comment]
it sounds like we're all on the same page here. I'll make a PR proposing alternate wording on that page

**Comment by SethTisue** [comment]
PR #958
