### ISSUE TITLE
"Testing on the command line" references nonexistent repo

### ISSUE THREAD

**Issue by cwphobia** [scala/docs.scala-lang#971]
The second instruction on the Getting Started page testing-scala-with-sbt-on-the-command-line.md fails because the referenced repository does not appear to exist.

"Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: git@github.com:scala/scalatest-example.g8.git: ERROR: Repository not found."

**Comment by SethTisue** [comment]
there is an in-progress attempt to address this at #959

**Comment by cwphobia** [comment]
Thanks for the pointer! I don't see a need to keep this one open, then.

**Comment by SethTisue** [comment]
oh, I see #959 doesn't actually have anything useful in it.

perhaps scalatest-example.g8 never actually existed, but was just something intended to be created...? in which case someone needs to create it. would someone like to make it in their own GitHub account, and then if it looks good, we can transfer it to the scala org?

**Comment by SethTisue** [comment]
@heathermiller or maybe you know who might have this already lying around...?

**Comment by Philippus** [comment]
this can be closed, more details here: scala/scala-lang/issues/755
