### ISSUE TITLE
out-of-order: def foldLeft[B](z: B)(op: (A,B) => B): B

### ISSUE THREAD

**Issue by chaokunyang** [scala/docs.scala-lang#975]
In https://docs.scala-lang.org/style/declarations.html
There is a out-of-order in MULTIPLE PARAMETER LISTS For type inference: 
```def foldLeft[B](z: B)(op: (A,B) => B): B``` should be changed to ```def foldLeft[B](z: B)(op: (B,A) => B): B```

**Comment by SethTisue** [comment]
agree. would you like to submit a pull request with the correction...?

**Comment by chaokunyang** [comment]
Of course, it would be my pleasure. I'll make a pull request later.

**Comment by chaokunyang** [comment]
the [pull request](https://github.com/scala/docs.scala-lang/pull/976) has be submitted
