### ISSUE TITLE
make "string interpolation" and "implicit classes" part of the tour

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#992]
@smarter points out on Gitter that:

> http://docs.scala-lang.org/overviews/core/implicit-classes.html is pretty bite-sized and http://docs.scala-lang.org/overviews/core/string-interpolation.html isn't so big either compared to some pages of the tour, and it's a pretty useful feature of Scala to know about

I agree, these could become part of http://docs.scala-lang.org/tour/tour-of-scala.html instead

**Comment by mghildiy** [comment]
Implicit classes is also mentioned in Implicits.md as part of work 'Rewrote implicits section of the tour #746'.

**Comment by SethTisue** [comment]
PR: #1004
