### ISSUE TITLE
Update the collections guide to the new collections framework

### ISSUE THREAD

**Issue by julienrf** [scala/docs.scala-lang#995]
http://docs.scala-lang.org/overviews/collections/introduction.html

Most of the content should be still valid. Here are the actions needed:
- make a new guide for 2.13 so that it coexists with the current guide (maybe not! we should first try to keep a single guide with version-specific sections when necessary),
- remove the “Traversable” page and merge it with the “Iterable” page,
- remove the “migrating from 2.7” page (only if we do two guides),
- add a page about non-strict collections: views, lazy list, iterators.

**Comment by SethTisue** [comment]
we should probably keep both the 2.11/2.12 and the 2.13 editions online, since people are still going to be using 2.11 and 2.12 for some years to come

**Comment by mghildiy** [comment]
Actions needed:
1. Merge trait-traversable with trait-iterable.
2. Remove migrating-from-scala-27

Am I right here?

**Comment by jvican** [comment]
I think so, @julienrf are you working on this or is this free to be picked up by contributors?

**Comment by julienrf** [comment]
@mghildiy I have updated the issue description with bullet points for the actions needed. You can try to give them a shot if you want.
