### ISSUE TITLE
Add a documentation page about migrating from 2.12 to 2.13

### ISSUE THREAD

**Issue by julienrf** [scala/docs.scala-lang#996]
I think we should have all the migration information (not just things about collections) in one page.

**Comment by SethTisue** [comment]
currently we do this in the Scala release notes, so e.g. the [2.12.0 release notes](https://github.com/scala/scala/releases/v2.12.0) also serve as our 2.11 -> 2.12 migration guide

the release itself is immutable but the release notes are not, so we can update them if new migration advice becomes available

keeping the release notes leaner and having them link to an external migration guide might be a better approach, though. for one thing, the release notes are only updatable directly by scala/scala maintainers, whereas having a separate migration guide would allow improvements to come in via pull request

**Comment by SethTisue** [comment]
closing since I'm not volunteering, I don't think @julienrf is either, and nobody else has

on the upside: the 2.13.0 release notes I assembled are quite comprehensive, so that's good
